OfficeDev/microsoft-365-agents-toolkit-samples

share-now/.vscode/launch.json
share-now/.vscode/settings.json
share-now/.vscode/tasks.json
todo-list-with-Azure-backend/.vscode/launch.json
todo-list-with-Azure-backend/.vscode/settings.json
todo-list-with-Azure-backend/.vscode/tasks.json

Update items under *.vscode/* folder to align with the latest toolkit version.
FYI, @xzf0587 (the share-now project), @formulahendry (the todo-list-with-Azure-backend project)

fix (local debug): update to latest version

---

share-now/.fx/settings.json

1. fix the setting name of message extension

fix message extension setting

---

share-now/README.md

1. update readme for local debug.

update share now readme

---

todo-list-with-Azure-backend/README.md
todo-list-with-Azure-backend/tabs/src/components/TabConfig.js

Fix:
- https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9950657
- https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9948052

fix(todo on azure): Update README, update UI of config page

---

share-now/tabs/package.json

1. remove useless package in tabs

remove useless package

---

todo-list-with-Azure-backend/README.md

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9960133

fix(todo on azure): Update README

---

in-meeting-app/.fx/env.default.json
in-meeting-app/bot/package.json

Including cross env to manage the env profile on different environments.
Change provision app service to free tier

Change provision resource to free tier and Fix bug about WSL

---

share-now/README.md
todo-list-with-Azure-backend/README.md

Minor format issue update and remove unsupported functions descriptions from share now.

format issue

---

share-now/.fx/manifest.source.json

1. update manifest to 1.10 from 1.7

update manifest version

---

faq-plus/bot/cards/askAnExpertCard.ts
faq-plus/bot/cards/responseCard.ts
faq-plus/bot/cards/smeTicketCard.ts
faq-plus/bot/cards/userNotificationCard.ts
faq-plus/bot/common/adaptiveHelper.ts
faq-plus/bot/common/constants.ts
faq-plus/bot/index.ts
faq-plus/bot/models/changeTicketStatusPayload.ts
faq-plus/bot/teamsbot.ts

Currently *bot\teamsBot.ts* `sendCardToTeamAsync()` can not successfully create conversation. @blackchoey

feat(sme card): send sme card to sme team and notify user

---

faq-plus/bot/cards/smeTicketCard.ts
faq-plus/bot/common/constants.ts
faq-plus/bot/providers/ticketsProvider.ts
faq-plus/bot/teamsbot.ts

Allow experts to update ticket status

feat: allow experts to update ticket status

---

faq-plus/bot/common/constants.ts
faq-plus/bot/teamsbot.ts
faq-plus/configapp/Microsoft.Teams.Apps.FAQPlusPlus.Configuration/Views/Home/Index.cshtml

1. Add fixed welcome message
2. Remove welcome message and help page related config in config app

feat: add fixed welcome message

---

faq-plus/bot/cards/askAnExpertCard.ts
faq-plus/bot/cards/smeTicketCard.ts
faq-plus/bot/cards/userNotificationCard.ts
faq-plus/bot/common/adaptiveHelper.ts
faq-plus/bot/common/constants.ts
faq-plus/bot/teamsbot.ts

1. Validate user input title
2. User notification card show "Unassigned" at first.
3. Convert time to user local time
4. Fix SME card type: 1) Chat with <expert> 2) "Unassigned" at first.

[FAQ-Plus] Tunning sample app behavior to align with original app 

---

faq-plus/bot/cards/responseCard.ts

fix(ask-an-expert): fix ask-an-expert button when answer is found

---

todo-list-with-Azure-backend/tabs/package-lock.json
todo-list-with-Azure-backend/tabs/package.json

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/9968359

fix(todo on azure): Upgrade react-scripts npm to fix high severity vulnerabilities

---

in-meeting-app/.fx/default.userdata
todo-list-with-Azure-backend/.fx/default.userdata

1. remove useless userdata files.

remove useless files

---

faq-plus/docs/deploy-qna-maker-services.md

1. Update doc to use arm template in main branch
2. Update the name of Azure search service

chore: update doc to use main branch and update azure search name

---

share-now/README.md
share-now/cli.md

1. add doc  to run share-now in cli.

add doc to run share-now in cli

---

todo-list-SPFx/.fx/manifest.source.json

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10241958

fix(spfx): disable spfx chat tab

---

todo-list-with-Azure-backend/README.md
todo-list-with-Azure-backend/cli.md

1. improve the doc of todo list with azure backend to run in cli

chore(todo-list-with-azure-backend): add cli doc

---

todo-list-with-Azure-backend/tabs/src/components/Creator.js

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10048485

fix(todo on azure): After deleting an item, 'Created By' is not refreshed

---

share-now/cli.md
todo-list-with-Azure-backend/cli.md

As teamsfx cli improved question model, remove the parameter input of provision in cli scenario, which will be asked in interactive model.

doc(share-now, todolist-with-azure): update provision command in cli

---

todo-list-SPFx/README.md

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10298315

doc: update spfx sample known issue

---

todo-list-SPFx/README.md

related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10298315

doc(spfx): update switch account issue cause

---

todo-list-with-Azure-backend/.github/workflows/cd.yml
todo-list-with-Azure-backend/.github/workflows/ci.yml
todo-list-with-Azure-backend/.github/workflows/provision.yml
todo-list-with-Azure-backend/README.md
todo-list-with-Azure-backend/create_table.sql
todo-list-with-Azure-backend/extract.js
todo-list-with-Azure-backend/package.json

to finish: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/10735214

feat: support cicd todolist azure

---

todo-list-SPFx/.vscode/launch.json
todo-list-SPFx/.vscode/tasks.json

feat(spfx): add teams workbench local debug support

---

todo-list-SPFx/README.md

1. Add Teams workbench in debug.
2. Refine the doc format.

doc(spfx): update spfx doc

---

todo-list-with-Azure-backend/.github/workflows/cd.yml
todo-list-with-Azure-backend/.github/workflows/provision.yml

align provision.yml for todolist with azure backend.

chore: align userdata content

---

bot-sso/bot/README.md
in-meeting-app/README.md
share-now/README.md
todo-list-with-Azure-backend/README.md

1. update command names for teams toolkit in VSCode.
2. update the wording of SQL firewall

chore(readme): update readme

---

todo-list-SPFx/cli.md

doc: update cli readme

---

NPM-search-connector-M365/README.md
todo-list-with-Azure-backend-M365/README.md

To fix https://github.com/OfficeDev/TeamsFx-Samples/pull/159:
- use aka link instead of review.docs link
- `Outlook Web Access` -> `Outlook Web Client`

doc(M365): update README

---

NPM-search-connector-M365/README.md
todo-list-with-Azure-backend-M365/README.md

doc(M365): fix typo in README

---

todo-list-with-Azure-backend/.github/workflows/cd.yml
todo-list-with-Azure-backend/.github/workflows/provision.yml
todo-list-with-Azure-backend/extract.js

upgrade cicd ymls.
to finish: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/12482241
**smoke tested by:** 
https://github.com/IvanJobs/CICDTest/runs/4208865766?check_suite_focus=true
https://github.com/IvanJobs/CICDTest/actions/runs/1461234714

chore: upgrade cicd ymls

---

hello-world-bot/.fx/configs/projectSettings.json
hello-world-tab-with-backend/.fx/configs/projectSettings.json
hello-world-tab/.fx/configs/projectSettings.json

1. Set `isFromSample` to be true.
2. Remove useless `projectId`.

fix: set isFromSample to be true

---

bot-sso/README.md
faq-plus/README.md
graph-toolkit-contact-exporter/README.md
hello-world-bot/README.md
hello-world-tab-with-backend/README.md
hello-world-tab/README.md
in-meeting-app/README.md
share-now/README.md
todo-list-with-Azure-backend/README.md

Port the changes from https://github.com/OfficeDev/TeamsFx-Samples/pull/190 and update other samples.

docs: add nodejs version prerequisite

---

faq-plus/README.md
share-now/README.md
todo-list-with-Azure-backend/README.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12681269

doc: use create *.env instead of open *.env

---

todo-list-with-Azure-backend-M365/tabs/package.json

Upgrade command: https://github.com/OfficeDev/TeamsFx/pull/3222
Sample in main branch: https://github.com/OfficeDev/TeamsFx-Samples/pull/213

fix(M365): update teams client sdk version

---

NPM-search-connector-M365/bot/package.json
bot-sso/bot/package.json
faq-plus/bot/package-lock.json
faq-plus/bot/package.json
hello-world-bot/bot/package.json
share-now/bot/package.json

Remove ngrok dependency from bot and message extension since installing global ngrok has been implemented in env checker.
Related to: https://github.com/OfficeDev/TeamsFx/pull/3311

fix: remove ngrok dependency from bot and message extension projects

---

NPM-search-connector-M365/.vscode/settings.json
NPM-search-connector-M365/.vscode/tasks.json
bot-sso/.vscode/settings.json
bot-sso/.vscode/tasks.json
faq-plus/.vscode/settings.json
faq-plus/.vscode/tasks.json
graph-toolkit-contact-exporter/.vscode/settings.json
graph-toolkit-contact-exporter/.vscode/tasks.json
hello-world-bot/.vscode/settings.json
hello-world-bot/.vscode/tasks.json
hello-world-tab-with-backend/.vscode/settings.json
hello-world-tab-with-backend/.vscode/tasks.json
hello-world-tab/.vscode/settings.json
hello-world-tab/.vscode/tasks.json
share-now/.vscode/settings.json
share-now/.vscode/tasks.json
todo-list-SPFx/.vscode/settings.json
todo-list-SPFx/.vscode/tasks.json
todo-list-with-Azure-backend-M365/.vscode/settings.json
todo-list-with-Azure-backend-M365/.vscode/tasks.json
todo-list-with-Azure-backend/.vscode/settings.json
todo-list-with-Azure-backend/.vscode/tasks.json

Related to: https://github.com/OfficeDev/TeamsFx/pull/3307

fix: update tasks/settings.json to support removing debug anyway

---

todo-list-with-Azure-backend/.github/workflows/cd.yml
todo-list-with-Azure-backend/.github/workflows/provision.yml

1. remove userdata
2. remove m365 ops
to finish: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/12941871

fix: remove userdata/m365ops

---

bot-sso/.gitignore

align .gitignore.
https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/13023097

chore: align gitignore

---

hello-world-tab-with-backend/.vscode/tasks.json
todo-list-with-Azure-backend-M365/.vscode/tasks.json

Remove "teamsfx: auth start" from tasks.json file.

fix: remove auth start tasks

---

NPM-search-connector-M365/.vscode/tasks.json
NPM-search-connector-M365/bot/package.json
bot-sso/.vscode/tasks.json
bot-sso/bot/package.json
faq-plus/.vscode/launch.json
faq-plus/.vscode/tasks.json
faq-plus/bot/package.json
graph-toolkit-contact-exporter/.vscode/tasks.json
graph-toolkit-contact-exporter/tabs/package.json
hello-world-bot/.vscode/tasks.json
hello-world-bot/bot/package.json
hello-world-tab-with-backend/.vscode/tasks.json
hello-world-tab-with-backend/api/package.json
hello-world-tab-with-backend/tabs/package.json
hello-world-tab/.vscode/tasks.json
hello-world-tab/tabs/package.json
share-now/.vscode/tasks.json
share-now/api/package.json
share-now/bot/package.json
share-now/tabs/package.json
todo-list-with-Azure-backend-M365/.vscode/tasks.json
todo-list-with-Azure-backend-M365/api/package.json
todo-list-with-Azure-backend-M365/tabs/package.json
todo-list-with-Azure-backend/.vscode/tasks.json
todo-list-with-Azure-backend/api/package.json
todo-list-with-Azure-backend/tabs/package.json

Support new F5 workflow to use `prerequisites check` and new task definitions in tasks.json.

feat: use latest local debug tasks

---

share-now/tabs/src/Website.tsx
share-now/tabs/src/app.tsx
share-now/templates/appPackage/manifest.local.template.json
share-now/templates/appPackage/manifest.remote.template.json

1. add the route of uri and content for website url.

chore(share-now): add uri for website

---

graph-toolkit-contact-exporter/tabs/public/auth-end.html
hello-world-tab-with-backend/tabs/public/auth-end.html
hello-world-tab/tabs/public/auth-end.html
todo-list-with-Azure-backend-M365/tabs/public/auth-end.html
todo-list-with-Azure-backend/tabs/public/auth-end.html

Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13352125?src=WorkItemMention&src-action=artifact_link

fix: fix auth end page

---

NPM-search-connector-M365/.vscode/launch.json
NPM-search-connector-M365/.vscode/tasks.json
bot-sso/.vscode/launch.json
bot-sso/.vscode/tasks.json
faq-plus/.vscode/launch.json
faq-plus/.vscode/tasks.json
graph-toolkit-contact-exporter/.vscode/launch.json
graph-toolkit-contact-exporter/.vscode/tasks.json
hello-world-bot/.vscode/launch.json
hello-world-bot/.vscode/tasks.json
hello-world-tab-with-backend/.vscode/launch.json
hello-world-tab-with-backend/.vscode/tasks.json
hello-world-tab/.vscode/launch.json
hello-world-tab/.vscode/tasks.json
share-now/.vscode/launch.json
share-now/.vscode/tasks.json
todo-list-with-Azure-backend-M365/.vscode/launch.json
todo-list-with-Azure-backend-M365/.vscode/tasks.json
todo-list-with-Azure-backend/.vscode/launch.json
todo-list-with-Azure-backend/.vscode/tasks.json

- remove launch configuration preLaunchTask: Start Frontend/Backend/Bot
- move Start Frontend/Backend/Bot to compound preLaunchTask
- update the endsPattern of bot problem matcher and show the bot problem
matcher details in tasks.json
Related to: https://github.com/OfficeDev/TeamsFx/pull/3937

chore(localdebug): use latest launch and task 

---

hello-world-tab-with-backend/tabs/package.json
hello-world-tab/tabs/package.json

fix https://github.com/OfficeDev/TeamsFx/issues/3929

fix: react app hangs after hot reload

---

.github/workflows/codeql-analysis.yml
faq-plus/bot/package-lock.json
faq-plus/configapp/Microsoft.Teams.Apps.FAQPlusPlus.Configuration/Views/Web.config
faq-plus/configapp/Microsoft.Teams.Apps.FAQPlusPlus.Configuration/Web.config
graph-toolkit-contact-exporter/tabs/package-lock.json
todo-list-SPFx/SPFx/package-lock.json
todo-list-SPFx/SPFx/package.json

https://github.com/OfficeDev/TeamsFx-Samples/pull/270
https://github.com/OfficeDev/TeamsFx-Samples/pull/269
https://github.com/OfficeDev/TeamsFx-Samples/pull/268
https://github.com/OfficeDev/TeamsFx-Samples/pull/265
https://github.com/OfficeDev/TeamsFx-Samples/pull/254

chore: update dep version

---

hello-world-tab-without-sso/README.md

related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13506467

fix(sample): fix typo in non sso tab

---

hello-world-tab-without-sso/README.md

Update readme since Graph Toolkit is merged into template. In this sample, we will not use Graph Toolkit in adding sso part.

docs(sample): update readme for non sso tab

---

hello-world-tab-without-sso/tabs/src/components/App.tsx

Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-3.1?workitem=13790146

fix: remove useless dependency

---

graph-toolkit-contact-exporter/tabs/package.json
graph-toolkit-contact-exporter/tabs/src/components/Tab.js

This issue is caused by latest graph toolkit change, and by default use people to list users which need admin consent

fix(graph-toolkit): fix 403 issue when list user

---

hello-world-tab-without-sso/README.md

Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/13882767

hotfix(non-sso): broken lib link for SDK 0.5.1

---

hello-world-tab-without-sso/tabs/src/components/App.tsx

fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY22-3.2?workitem=13883051

fix: remove useless bracket

---

graph-toolkit-contact-exporter/tabs/package.json
hello-world-in-meeting/tabs/package.json
hello-world-tab-with-backend/api/package.json
hello-world-tab-with-backend/tabs/.env
hello-world-tab-with-backend/tabs/package.json
hello-world-tab-without-sso/tabs/package.json
hello-world-tab/tabs/package.json
share-now/api/package.json
share-now/tabs/package.json
todo-list-with-Azure-backend-M365/api/package.json
todo-list-with-Azure-backend-M365/tabs/package.json
todo-list-with-Azure-backend/api/package.json
todo-list-with-Azure-backend/tabs/package.json

1. Remove unused dev dependencies.
2. Add script `"test": "echo \"Error: no test specified\" && exit 1"`.
3. Add missed .env file in hello-world-tab-with-backend sample.

chore: remove unused dev dependencies and add placeholder test script

---

bot-sso/.fx/configs/projectSettings.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14124491

chore: remove project id

---

incoming-webhook-notification/README.md

Fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14135449/

docs: update incoming webhook readme

---

share-now/tabs/package.json

update package json for the dependent react version upgrade.

chore(sharenow): update package.json

---

todo-list-SPFx/templates/appPackage/manifest.template.json

Tested and works after the fix

fix: local debug spfx sample app fail

---

adaptive-card-notification/bot/tsconfig.json
bot-sso/bot/tsconfig.json
faq-plus/bot/tsconfig.json
graph-connector-app/api/tsconfig.json
hello-world-bot/bot/tsconfig.json
hello-world-tab-with-backend/api/tsconfig.json
share-now/api/tsconfig.json

https://github.com/OfficeDev/TeamsFx/issues/4953#issuecomment-1120979504

chore: skip lib check to work around build error

---

NPM-search-connector-M365/package.json
adaptive-card-notification/package.json
bot-sso/bot/package.json
bot-sso/package.json
graph-connector-app/package.json
graph-toolkit-contact-exporter/package.json
hello-world-bot/package.json
hello-world-in-meeting/package.json
hello-world-tab-with-backend/package.json
hello-world-tab-without-sso/package.json
hello-world-tab/package.json
todo-list-with-Azure-backend-M365/package.json
todo-list-with-Azure-backend/package.json

https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14472740
1. Upgrade cli devDependency to 1.*
2. Upgrade sdk ref to ^1.0.0

chore: update bot sso

---

hello-world-bot/.fx/configs/azure.parameters.dev.json

Fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/14483360/

fix: resolve token bug in azure parameter json file

---

adaptive-card-notification/bot/.gitignore
adaptive-card-notification/bot/package.json
incoming-webhook-notification/incoming-webhook/package.json

Detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14472704

fix(notification): update teamsfx sdk version

---

share-now/tabs/package.json

Downgrade the react version to support npm version 8.x.x

chore(sharenow): fix react version

---

NPM-search-connector-M365/README.md
README.md
adaptive-card-notification/README.md
bot-sso/README.md
faq-plus/README.md
graph-connector-app/README.md
graph-toolkit-contact-exporter/README.md
hello-world-bot/README.md
hello-world-in-meeting/README.md
hello-world-tab-with-backend/README.md
hello-world-tab-without-sso/README.md
hello-world-tab/README.md
incoming-webhook-notification/README.md
share-now/README.md
todo-list-SPFx/README.md
todo-list-with-Azure-backend-M365/README.md
todo-list-with-Azure-backend/README.md

1. removed preview related texts 
2. updated Node versions in pre-requisites
3. removed unnecessary older version in pre-requisite

update sample readmes

---

bot-sso/bot/helpers/ssoDialog.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14485398

chore: refine message

---

share-now/tabs/package.json
share-now/tabs/tsconfig.json

1. remove resolution before npm install
2. add react path to resolve
The problem of Ajv is caused by react-script update. 
Refer to https://github.com/facebook/create-react-app/issues/12155 for the root cause.
Refer to https://github.com/facebook/react/issues/24304#issuecomment-1111184798 for fixing it.

chore(sharenow): remove resolution and add react path

---

graph-connector-app/tabs/src/components/sample/Ingest.tsx
graph-connector-app/tabs/src/components/sample/lib/apiClient.ts
hello-world-tab-with-backend/tabs/src/components/sample/AzureFunctions.tsx
todo-list-with-Azure-backend-M365/.fx/configs/azure.parameters.dev.json
todo-list-with-Azure-backend-M365/tabs/src/components/Tab.js
todo-list-with-Azure-backend/tabs/src/components/Tab.js

demonstrate how to use createApiClient in our samples

chore: use createApiClient in samples

---

todo-list-SPFx/SPFx/.eslintrc.js
todo-list-SPFx/SPFx/src/webparts/todoList/components/Profile.tsx
todo-list-SPFx/SPFx/src/webparts/todoList/components/ProfileProps.ts
todo-list-SPFx/SPFx/src/webparts/todoList/components/SharePointListManager.ts
todo-list-SPFx/SPFx/src/webparts/todoList/components/TodoList.tsx

1. Enable eslint rules and fix the alerts
2. Fix the issue that completion status keeps check after check and uncheck todo item

fix: fix eslint alerts and todo item completion issue

---

adaptive-card-notification/bot/package.json
adaptive-card-notification/bot/tsconfig.json
bot-sso/bot/package.json
bot-sso/bot/tsconfig.json
faq-plus/bot/package.json
faq-plus/bot/tsconfig.json
graph-connector-app/api/package.json
graph-connector-app/api/tsconfig.json
hello-world-bot/bot/package.json
hello-world-bot/bot/tsconfig.json
hello-world-tab-with-backend/api/package.json
hello-world-tab-with-backend/api/tsconfig.json
incoming-webhook-notification/incoming-webhook/package.json
share-now/api/package.json
share-now/api/tsconfig.json
share-now/bot/package.json
share-now/bot/tsconfig.json

[https://github.com/OfficeDev/TeamsFx/issues/4953#issuecomment-1120979504](https://github.com/OfficeDev/TeamsFx/issues/4953#issuecomment-1120979504)
Update typescript and ts-node version, and remove skip lib check.

chore: update ts and ts-node version

---

todo-list-SPFx/SPFx/.eslintrc.js

fix this bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15195056

fix: eslint error during spfx sample app build package

---

incoming-webhook-notification/incoming-webhook/package.json
share-now/bot/package.json

Unexpected comma caused deploy failed, and delete comma to fix the bug.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15194643

fix: delete unexpected comma in json files

---

todo-list-SPFx/README.md

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15263893?src=WorkItemMention&src-action=artifact_link

chore: update supported node version for spfx

---

NPM-search-connector-M365/templates/azure/provision/bot.bicep
adaptive-card-notification/templates/azure/provision/bot.bicep
bot-sso/templates/azure/provision/bot.bicep
faq-plus/templates/azure/provision/bot.bicep
graph-connector-app/templates/azure/provision/function.bicep
graph-toolkit-productivity-hub-aspnetcore/OneProductivityHubAspNetCore/Templates/azure/provision/webapp.bicep
hello-world-bot/templates/azure/provision/bot.bicep
hello-world-tab-with-backend/templates/azure/provision/function.bicep
share-now/templates/azure/provision/bot.bicep
share-now/templates/azure/provision/function.bicep
todo-list-with-Azure-backend-M365/templates/azure/provision/function.bicep
todo-list-with-Azure-backend/templates/azure/provision/function.bicep

add "properties" key in "serverfarm" resource in "*.bicep"s to fix the provision bug

[fix]add "properties" key in "serverfarm" resource

---

hello-world-tab-with-backend/api/getUserProfile/index.ts

1. Add app credential in Azure function as comments to show how to use application permission to call graph api.
2. As the admin consent is needed in application permission, we add the codes as comments.

chore(comment): add app credential in Azure function as comments

---

NPM-search-connector-M365/.vscode/launch.json
adaptive-card-notification/.vscode/launch.json
bot-sso/.vscode/launch.json
faq-plus/.vscode/launch.json
graph-connector-app/.vscode/launch.json
graph-connector-bot/.vscode/launch.json
graph-toolkit-contact-exporter/.vscode/launch.json
graph-toolkit-one-productivity-hub/.vscode/launch.json
hello-world-bot/.vscode/launch.json
hello-world-in-meeting/.vscode/launch.json
hello-world-tab-with-backend/.vscode/launch.json
hello-world-tab-without-sso/.vscode/launch.json
hello-world-tab/.vscode/launch.json
share-now/.vscode/launch.json
stocks-update-notification-bot/.vscode/launch.json
todo-list-SPFx/.vscode/launch.json
todo-list-with-Azure-backend-M365/.vscode/launch.json
todo-list-with-Azure-backend/.vscode/launch.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15525732/
Hide debug console for all web client launch sessions.

fix(all): hide debug console for teams web client

---

query-org-user-with-message-extension-sso/README.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15594122

chore: fix typo

---

graph-connector-app/api/package.json

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15590576

fix(graph-connector-tab): add missing devDependencies

---

hello-world-in-meeting/templates/appPackage/manifest.template.json

chore: simple manifest in in-meeting app

---

query-org-user-with-message-extension-sso/README.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16108199

docs: add ngrok config in readme

---

NPM-search-connector-M365/README.md
adaptive-card-notification/README.md
graph-connector-app/README.md
graph-toolkit-contact-exporter/README.md
graph-toolkit-one-productivity-hub/README.md
graph-toolkit-productivity-hub-aspnetcore/README.md
hello-world-tab-with-backend/README.md
hello-world-tab-without-sso/README.md
hello-world-tab/README.md
incoming-webhook-notification/README.md
share-now/README.md
stocks-update-notification-bot/README.md
todo-list-SPFx/README.md
todo-list-with-Azure-backend-M365/README.md
todo-list-with-Azure-backend/README.md

Replace readme path with absolute path.

chore(update): update readme

---

adaptive-card-notification/bot/src/internal/config.ts
adaptive-card-notification/bot/src/internal/initialize.ts
command-bot-with-sso/bot/src/authConfig.ts
command-bot-with-sso/bot/src/internal/config.ts
command-bot-with-sso/bot/src/internal/initialize.ts
query-org-user-with-message-extension-sso/bot/config.ts
query-org-user-with-message-extension-sso/bot/index.ts
query-org-user-with-message-extension-sso/bot/teamsBot.ts

ADO task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_git/teamsfx-specs/pullrequest/6505698?path=/specs/app-setting-improvement.md&_a=files
Add config.ts/js to include all the configs

chore: app settings for samples

---

NPM-search-connector-M365/teamsfx/app.local.yml
bot-sso/teamsfx/app.local.yml
hello-world-bot/teamsfx/app.local.yml
hello-world-tab/teamsfx/app.local.yml
stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/teamsfx/app.local.yml
stocks-update-notification-bot/teamsfx/app.local.yml
todo-list-with-Azure-backend-M365/teamsfx/app.local.yml

- botFramework/createOrUpdateBot -> botFramework/create
- env/generate -> file/updateEnv

chore: rename botFramework and env action

---

teams-videoapp-sample/.vscode/launch.json

fix: fix macos test app path

---

bot-sso/index.ts
bot-sso/package.json
hello-world-bot/index.ts
hello-world-bot/package.json

Reverts OfficeDev/TeamsFx-Samples#562

Revert "chore: use cloudAdapter for bot sso and hello world bot"

---

NPM-search-connector-M365/teamsfx/app.local.yml
adaptive-card-notification/teamsfx/app.local.yml
bot-sso/teamsfx/app.local.yml
hello-world-bot-with-tab/teamsfx/app.local.yml
hello-world-bot/teamsfx/app.local.yml
stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/teamsfx/app.local.yml
stocks-update-notification-bot/teamsfx/app.local.yml
todo-list-with-Azure-backend-M365/teamsfx/app.local.yml

- rename actions in m365 projects by the way

chore(debug): add channels to botFramework action in v3 templates

---

NPM-search-connector-M365/teamsfx/app.local.yml
adaptive-card-notification/teamsfx/app.local.yml
bot-sso/teamsfx/app.local.yml
hello-world-bot-with-tab/teamsfx/app.local.yml
hello-world-bot/teamsfx/app.local.yml
hello-world-in-meeting/teamsfx/app.local.yml
hello-world-tab-with-backend/teamsfx/app.local.yml
hello-world-tab/teamsfx/app.local.yml
query-org-user-with-message-extension-sso/teamsfx/app.local.yml
stocks-update-notification-bot/teamsfx/app.local.yml
todo-list-SPFx/teamsfx/app.local.yml
todo-list-with-Azure-backend-M365/teamsfx/app.local.yml

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16727894/.

chore: rename teamsApp action arg in app.local.yml

---

todo-list-SPFx/teamsfx/.env.dev
todo-list-SPFx/teamsfx/.env.local

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16774371

fix: add env files for todo-list-spfx sample

---

NPM-search-connector-M365/templates/azure/provision/bot.bicep
bot-sso/templates/azure/provision/bot.bicep
command-bot-with-sso/templates/azure/provision/webapp.bicep
graph-connector-bot/templates/azure/provision/bot.bicep
hello-world-bot/templates/azure/provision/bot.bicep
place-your-order-workflow-bot/templates/azure/provision/azureWebAppBot.bicep
query-org-user-with-message-extension-sso/templates/azure/provision/webapp.bicep
share-now/templates/azure/provision/bot.bicep

detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16936740

chore(v2): upgrade WEBSITE_NODE_DEFAULT_VERSION of Azure App Service to 18

---

NPM-search-connector-M365/README.md
adaptive-card-notification/README.md
bot-sso/README.md
command-bot-with-sso/README.md
deep-linking-hello-world-tab-without-sso-M365/README.md
graph-connector-app/README.md
graph-connector-bot/README.md
graph-toolkit-contact-exporter/README.md
graph-toolkit-one-productivity-hub/README.md
hello-world-bot/README.md
hello-world-in-meeting/README.md
hello-world-tab-with-backend/README.md
hello-world-tab-without-sso/README.md
hello-world-tab/README.md
incoming-webhook-notification/README.md
place-your-order-workflow-bot/README.md
query-org-user-with-message-extension-sso/README.md
share-now/README.md
stocks-update-notification-bot/README.md
teams-videoapp-sample/README.md
todo-list-with-Azure-backend-M365/README.md
todo-list-with-Azure-backend/README.md

detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16936740

docs(v2): update the supported node versions in README

---

adaptive-card-notification/teamsapp.yml

Update action comments to make it more clear, clarify they're target for different platform.

chore: update comments to clarify target platform

---

bot-sso/index.ts
bot-sso/package.json

sync with https://github.com/OfficeDev/TeamsFx-Samples/pull/637
Hello-world-bot not updated since it's not in v3 sample anymore.

chore: update bot-sso to use cloud Adapter

---

team-central-dashboard/api/finishTaskNotification/getInstallationId.ts
team-central-dashboard/api/finishTaskNotification/index.ts
team-central-dashboard/teamsapp.local.yml
team-central-dashboard/teamsapp.yml

fix: fix dashboard notification bug

---

adaptive-card-notification/src/internal/responseWrapper.ts
stocks-update-notification-bot/src/internal/messageHandler.ts
stocks-update-notification-bot/src/internal/responseWrapper.ts

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17148627/ and https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17149060.

chore(v3): fix stocks update and adaptive card sample build error

---

team-central-dashboard/teamsapp.local.yml
team-central-dashboard/teamsapp.yml

Fix the issue of [dashboard deployment failure](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17148883/).

fix: deployment failure issues

---

adaptive-card-notification/src/internal/responseWrapper.ts
stocks-update-notification-bot/src/internal/responseWrapper.ts

Sync with https://github.com/OfficeDev/TeamsFx/pull/7730

fix: fix send in responseWrapper

---

team-central-dashboard/env/.env.dev
team-central-dashboard/env/.env.local

Fix [[V3] sample dashboard lost env folder and relative env files](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17200978/).

chore: add env files

---

hello-world-bot-with-tab/teamsapp.yml

fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17264375/

fix: build both tab and bot

---

team-central-dashboard/src/services/chartService.ts
team-central-dashboard/src/services/documentService.ts
team-central-dashboard/src/services/taskService.ts

Modify `replace` to `replaceAll`.

chore: replaceAll

---

NPM-search-connector-M365/.vscode/tasks.json
adaptive-card-notification/.vscode/tasks.json
bot-sso/.vscode/tasks.json
command-bot-with-sso/.vscode/tasks.json
graph-connector-app/.vscode/tasks.json
graph-toolkit-contact-exporter/.vscode/tasks.json
hello-world-bot-with-tab/.vscode/tasks.json
hello-world-bot/.vscode/tasks.json
hello-world-in-meeting/.vscode/tasks.json
hello-world-tab-with-backend/.vscode/tasks.json
hello-world-tab/.vscode/tasks.json
query-org-user-with-message-extension-sso/.vscode/tasks.json
share-now/.vscode/tasks.json
stocks-update-notification-bot/.vscode/tasks.json
team-central-dashboard/.vscode/tasks.json
todo-list-SPFx/.vscode/tasks.json
todo-list-with-Azure-backend-M365/.vscode/tasks.json
todo-list-with-Azure-backend/.vscode/tasks.json

- remove template arg
- "Create resources" -> "Provision"
- "Build project" -> "Deploy"

chore(debug): update provison and deploy task

---

query-org-user-with-message-extension-sso/package.json

fix issue:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17335903

chore: fix restify version to support node 18

---

todo-list-with-Azure-backend-M365/.vscode/launch.json
todo-list-with-Azure-backend-M365/README.md
todo-list-with-Azure-backend-M365/cli.md

Related: https://github.com/OfficeDev/TeamsFx/pull/7857

chore(v3-m365): rename "Office.com" to "Microsoft 365 app"

---

.github/CODEOWNERS

assign codeowner according to this task
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-2.2?workitem=16299096

chore: add sample codeowners

---

NPM-search-connector-M365/.vscode/tasks.json
adaptive-card-notification/.vscode/tasks.json
bot-sso/.vscode/tasks.json
command-bot-with-sso/.vscode/tasks.json
graph-connector-bot/.vscode/tasks.json
hello-world-bot-with-tab/.vscode/tasks.json
query-org-user-with-message-extension-sso/.vscode/tasks.json
share-now/.vscode/tasks.json
stocks-update-notification-bot/.vscode/tasks.json

detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17382761/

chore(localdebug): change ngrok to basis

---

hello-world-in-meeting/README.md
hello-world-in-meeting/src/components/Tab.jsx

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17292817

chore: introduce app caching v3

---

todo-list-with-Azure-backend/teamsapp.local.yml

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17470477

fix(v3): install dotnet for todo-list

---

hello-world-teams-tab-and-outlook-add-in/README.md

Update README.md format

---

graph-toolkit-contact-exporter/README.md
hello-world-tab/README.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17403430

docs: add note for auth code flow limitations on mobile

---

todo-list-with-Azure-backend/.vscode/tasks.json
todo-list-with-Azure-backend/teamsapp.local.yml

Fix https://msazure.visualstudio.com/9660fff2-2363-48b0-9e15-64df2283e932/_workitems/edit/17470477

fix: add execPath for dotnet

---

hello-world-teams-tab-and-outlook-add-in/README.md
hello-world-teams-tab-and-outlook-add-in/add-in/webpack.config.js
hello-world-teams-tab-and-outlook-add-in/appPackage/manifest.json

Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17550877
and update manifest.json to conform to JSON schema

chore: update README.md to include Preview Remote for add-in

---

query-org-user-with-message-extension-sso/appPackage/manifest.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-3.1?workitem=17550095

chore(me): remove the create card action on manifest

---

NPM-search-connector-M365/infra/azure.bicep
NPM-search-connector-M365/teamsapp.yml
bot-sso/infra/azure.bicep
bot-sso/teamsapp.yml
command-bot-with-sso/infra/azure.bicep
command-bot-with-sso/teamsapp.yml
graph-connector-app/teamsapp.yml
graph-connector-bot/teamsapp.yml
hello-world-tab-with-backend/infra/azure.bicep
hello-world-tab-with-backend/teamsapp.yml
share-now/teamsapp.yml
stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/teamsapp.yml
stocks-update-notification-bot/teamsapp.yml
todo-list-with-Azure-backend-M365/teamsapp.yml
todo-list-with-Azure-backend/teamsapp.yml

fix: fix bad aka links

---

command-bot-with-sso/README.md
graph-toolkit-contact-exporter/README.md
graph-toolkit-one-productivity-hub/README.md

[Task 17554204](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17554204): update README for samples

docs: update README.md for V3

---

NPM-search-connector-M365/.vscode/launch.json
adaptive-card-notification/.vscode/launch.json
bot-sso/.vscode/launch.json
command-bot-with-sso/.vscode/launch.json
deep-linking-hello-world-tab-without-sso-M365/.vscode/launch.json
developer-assist-dashboard/.vscode/launch.json
graph-connector-app/.vscode/launch.json
graph-connector-bot/.vscode/launch.json
graph-toolkit-contact-exporter/.vscode/launch.json
graph-toolkit-one-productivity-hub/.vscode/launch.json
hello-world-bot-with-tab/.vscode/launch.json
hello-world-in-meeting/.vscode/launch.json
hello-world-tab-with-backend/.vscode/launch.json
hello-world-teams-tab-and-outlook-add-in/.vscode/launch.json
query-org-user-with-message-extension-sso/.vscode/launch.json
share-now/.vscode/launch.json
stocks-update-notification-bot/.vscode/launch.json
team-central-dashboard/.vscode/launch.json
todo-list-SPFx/.vscode/launch.json
todo-list-with-Azure-backend-M365/.vscode/launch.json
todo-list-with-Azure-backend/.vscode/launch.json
whos-next-meeting-app/.vscode/launch.json

- replace `${teamsAppId}` with `${{TEAMS_APP_ID}}`
- replace `${teamsAppInternalId}` with `${{M365_APP_ID}}`
Related: https://github.com/OfficeDev/TeamsFx/pull/8128

chore: use env reference in launch.json

---

.github/CODEOWNERS
hello-world-teams-tab-and-outlook-add-in/.gitignore
hello-world-teams-tab-and-outlook-add-in/.vscode/launch.json
hello-world-teams-tab-and-outlook-add-in/README.md
hello-world-teams-tab-and-outlook-add-in/add-in/package.json
hello-world-teams-tab-and-outlook-add-in/appPackage/manifest.json
hello-world-teams-tab-and-outlook-add-in/env/.env.dev
hello-world-teams-tab-and-outlook-add-in/env/.env.local

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17754565
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17552080
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-3.2?workitem=17552044
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17665082

update outlook add-in sample

---

NPM-search-message-extension-codespaces/teamsapp.yml
adaptive-card-notification/teamsapp.yml
graph-connector-bot/teamsapp.yml
stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/teamsapp.local.yml
stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/teamsapp.yml
stocks-update-notification-bot/teamsapp.yml

chore: update botaadapp output

---

adaptive-card-notification/teamsapp.local.yml
graph-connector-bot/teamsapp.local.yml

chore: refine comments

---

adaptive-card-notification/README.md
incoming-webhook-notification/README.md
stocks-update-notification-bot-dotnet/README.md
stocks-update-notification-bot/README.md

[Task 17554185](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17554185): Update README file for sample owned by xiaofu

docs(v5): Update README file for sample

---

hello-world-teams-tab-and-outlook-add-in/README.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17554236

docs: update README

---

graph-connector-app/teamsapp.local.yml

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17863531

fix: remove invalid writeToEnvironmentFile

---

graph-connector-app/tabs/package.json

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17863531

fix: add missing @fluentui/react

---

developer-assist-dashboard/teamsapp.yml

Fix this P0 bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17900032

fix: remove projectId from teamsapp.yml

---

NPM-search-connector-M365/cli.md
bot-sso/README.md
command-bot-with-sso/README.md
hello-world-bot-with-tab/README.md

detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17825928

docs(localdebug): add start local tunnel into cli preview steps

---

hello-world-tab-with-backend/teamsapp.local.yml
hello-world-tab-with-backend/teamsapp.yml
todo-list-SPFx/teamsapp.yml

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17900012

fix: teamsApp/update have no output

---

graph-connector-app/teamsapp.yml

Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17900026

fix(graph-connector): remove invalid writeToEnvironmentFile

---

todo-list-SPFx/teamsapp.yml

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17900023

fix: remove unused field in teamsApp/update action

---

todo-list-SPFx/src/.eslintrc.js
todo-list-SPFx/src/config/serve.json
todo-list-SPFx/src/src/webparts/todoList/components/ITodoListState.ts
todo-list-SPFx/src/src/webparts/todoList/components/Profile.tsx
todo-list-SPFx/src/src/webparts/todoList/components/SharePointListManager.ts
todo-list-SPFx/src/src/webparts/todoList/components/TodoList.tsx
todo-list-SPFx/src/src/webparts/todoList/components/index.d.ts
todo-list-SPFx/src/tsconfig.json

Cherry-pick https://github.com/OfficeDev/TeamsFx-Samples/pull/573
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17980611

fix: deploy fail when running gulp bundle task

---

developer-assist-dashboard/teamsapp.yml

To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/18009636

fix: dev dashboard yaml issue

---

NPM-search-connector-M365/appPackage/manifest.json
NPM-search-message-extension-codespaces/appPackage/manifest.json
adaptive-card-notification/appPackage/manifest.json
developer-assist-dashboard/appPackage/manifest.json
graph-toolkit-contact-exporter/appPackage/manifest.json
graph-toolkit-one-productivity-hub/appPackage/manifest.json
hello-world-bot-with-tab/appPackage/manifest.json
hello-world-in-meeting/appPackage/manifest.json
hello-world-tab-codespaces/appPackage/manifest.json
notification-codespaces/appPackage/manifest.json
query-org-user-with-message-extension-sso/appPackage/manifest.json
share-now/appPackage/manifest.json
stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/appPackage/manifest.json
todo-list-SPFx/appPackage/manifest.json
todo-list-SPFx/appPackage/manifest.local.json
todo-list-with-Azure-backend-M365/appPackage/manifest.json
todo-list-with-Azure-backend/appPackage/manifest.json

P1 bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17957778

refactor: upgrade manifest version to 1.16

---

query-org-user-with-message-extension-sso/config.ts
query-org-user-with-message-extension-sso/teamsBot.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-4.2?workitem=17969231

fix: fix remote query sso link without https surffix

---

NPM-search-connector-M365/teamsapp.local.yml
NPM-search-connector-M365/teamsapp.yml
NPM-search-message-extension-codespaces/teamsapp.local.yml
NPM-search-message-extension-codespaces/teamsapp.yml
adaptive-card-notification/teamsapp.local.yml
adaptive-card-notification/teamsapp.yml
bot-sso/teamsapp.local.yml
bot-sso/teamsapp.yml
command-bot-with-sso/teamsapp.local.yml
command-bot-with-sso/teamsapp.yml
graph-connector-bot/teamsapp.local.yml
graph-connector-bot/teamsapp.yml
hello-world-bot-with-tab/teamsapp.local.yml
hello-world-bot-with-tab/teamsapp.yml
notification-codespaces/teamsapp.local.yml
notification-codespaces/teamsapp.yml
query-org-user-with-message-extension-sso/teamsapp.local.yml
query-org-user-with-message-extension-sso/teamsapp.yml
share-now/teamsapp.local.yml
share-now/teamsapp.yml
stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/teamsapp.local.yml
stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/teamsapp.yml
stocks-update-notification-bot/teamsapp.local.yml
stocks-update-notification-bot/teamsapp.yml

Fix the error of action botAadApp/create

style: lint botaadapp action in yaml

---

graph-connector-app/teamsapp.local.yml
graph-connector-app/teamsapp.yml
hello-world-tab-with-backend/teamsapp.local.yml
hello-world-tab-with-backend/teamsapp.yml
todo-list-SPFx/teamsapp.local.yml

1) Some lint error
2) output from ./build/appPackage to ./appPackage/build

style: some lint and path error

---

graph-connector-app/tabs/src/components/sample/Welcome.css
graph-connector-app/tabs/src/index.css
hello-world-bot-with-tab/tab/src/components/sample/Welcome.css
hello-world-bot-with-tab/tab/src/index.css
hello-world-tab-codespaces/src/components/sample/Welcome.css
hello-world-tab-codespaces/src/index.css
hello-world-tab-with-backend/src/components/sample/Welcome.css
hello-world-tab-with-backend/src/index.css
hello-world-teams-tab-and-outlook-add-in/tab/src/components/sample/Welcome.css
hello-world-teams-tab-and-outlook-add-in/tab/src/index.css

Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Teams%20Extensibility%20E2E%20Team/Microsoft%20Teams%20Extensibility/CY23-4.2?workitem=18314836

fix: fix ios display error

---

NPM-search-connector-M365/README.md
adaptive-card-notification/README.md
bot-sso/README.md
command-bot-with-sso/README.md
deep-linking-hello-world-tab-without-sso-M365/README.md
developer-assist-dashboard/README.md
graph-connector-app/README.md
graph-connector-bot/README.md
graph-toolkit-contact-exporter/README.md
graph-toolkit-one-productivity-hub/README.md
hello-world-bot-with-tab/README.md
hello-world-in-meeting/README.md
hello-world-tab-with-backend/README.md
hello-world-tab-with-backend/api/README.md
hello-world-teams-tab-and-outlook-add-in/README.md
query-org-user-with-message-extension-sso/README.md
share-now/README.md
stocks-update-notification-bot/README.md
team-central-dashboard/README.md
todo-list-SPFx/README.md
todo-list-with-Azure-backend-M365/README.md
todo-list-with-Azure-backend/README.md
whos-next-meeting-app/README.md

Feature Id: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16382343/

docs: update ttk version in readme

---

bot-sso/.vscode/tasks.json
command-bot-with-sso/.vscode/tasks.json
developer-assist-dashboard/.vscode/tasks.json
graph-connector-app/.gitignore
graph-connector-app/.vscode/tasks.json
graph-connector-app/teamsapp.local.yml
graph-connector-bot/.vscode/tasks.json
graph-toolkit-one-productivity-hub/.vscode/tasks.json
hello-world-tab-with-backend/.gitignore
hello-world-tab-with-backend/.vscode/tasks.json
hello-world-tab-with-backend/teamsapp.local.yml
hello-world-teams-tab-and-outlook-add-in/.vscode/tasks.json
query-org-user-with-message-extension-sso/.vscode/tasks.json
team-central-dashboard/.gitignore
team-central-dashboard/.vscode/tasks.json
team-central-dashboard/teamsapp.local.yml
todo-list-with-Azure-backend/.vscode/tasks.json

detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/19317555

fix: add missing func installation in yaml and update task.json to the latest schema

---

NPM-search-connector-M365/.gitignore
NPM-search-message-extension-codespaces/.gitignore
adaptive-card-notification/.gitignore
bot-sso/.gitignore
command-bot-with-sso/.gitignore
developer-assist-dashboard/.gitignore
graph-connector-app/.gitignore
graph-connector-bot/.gitignore
graph-toolkit-contact-exporter/.gitignore
graph-toolkit-one-productivity-hub/.gitignore
hello-world-bot-with-tab/.gitignore
hello-world-in-meeting/.gitignore
hello-world-tab-codespaces/.gitignore
hello-world-tab-with-backend/.gitignore
hello-world-teams-tab-and-outlook-add-in/.gitignore
notification-codespaces/.gitignore
query-org-user-with-message-extension-sso/.gitignore
share-now/.gitignore
stocks-update-notification-bot/.gitignore
team-central-dashboard/.gitignore
todo-list-SPFx/.gitignore
todo-list-with-Azure-backend-M365/.gitignore
todo-list-with-Azure-backend/.gitignore
whos-next-meeting-app/.gitignore

Related PR: https://github.com/OfficeDev/TeamsFx/pull/8515
Issue: https://github.com/OfficeDev/TeamsFx/issues/8489

fix: update gitignore for appPackage/build

---

hello-world-teams-tab-and-outlook-add-in/README.md

Fixes doc
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/19505549

docs: add link for switching outlook update channels

---

hello-world-bot-with-tab/appPackage/manifest.json
hello-world-bot-with-tab/tab/src/components/App.tsx
hello-world-in-meeting/appPackage/manifest.json
hello-world-in-meeting/src/components/TabConfig.jsx
hello-world-tab-with-backend/appPackage/manifest.json
hello-world-tab-with-backend/src/components/App.tsx

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17940852/

perf: enable loading indicator

---

graph-connector-app/tabs/src/index.css
hello-world-bot-with-tab/tab/src/index.css
hello-world-tab-codespaces/src/index.css
hello-world-tab-with-backend/src/index.css
hello-world-teams-tab-and-outlook-add-in/tab/src/index.css

Bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21333006

fix: fix mobile tab app display error

---

adaptive-card-notification/README.md

detail: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21593946

docs: update remote preview bot endpoint env name in sample adaptivecard README

---

developer-assist-dashboard/src/services/callFunction.ts
graph-connector-app/tabs/src/components/sample/Ingest.tsx
hello-world-bot-with-tab/tab/src/components/sample/Deploy.tsx
hello-world-tab-codespaces/src/components/sample/Deploy.jsx
hello-world-tab-with-backend/src/components/sample/AzureFunctions.tsx
hello-world-tab-with-backend/src/components/sample/Deploy.tsx
hello-world-teams-tab-and-outlook-add-in/tab/src/components/sample/Deploy.tsx
team-central-dashboard/src/services/callFunction.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21425621

fix: tab's content should be consistent with VSC command palette

---

developer-assist-dashboard/appPackage/manifest.json
team-central-dashboard/appPackage/manifest.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21444433/

fix: using dev-tunnel in mobile conflict with loading indicator

---

todo-list-SPFx/README.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21455865

docs: update SPFx sample readme

---

share-now/tabs/package.json
share-now/tabs/src/api/axios-decorator.ts
share-now/tabs/src/components/add-new-dialog/add-new-dialog-content.tsx
share-now/tabs/src/components/card-view/discover-wrapper-page.tsx
share-now/tabs/src/components/card-view/popup-more-menu.tsx
share-now/tabs/src/components/edit-dialog/edit-dialog-content.tsx
share-now/tabs/src/configVariables.ts

Fix bug: https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/19027362

fix(sharenow): fix build warning

---

NPM-search-connector-M365/web.config
NPM-search-message-extension-codespaces/web.config
hello-world-bot-with-tab/bot/web.config
notification-codespaces/web.config
query-org-user-with-message-extension-sso/web.config

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21593945

fix: fix broken links in web.config

---

bot-sso/.webappignore
bot-sso/web.config
command-bot-with-sso/.webappignore
command-bot-with-sso/web.config
graph-connector-bot/.webappignore
graph-connector-bot/web.config
share-now/bot/web.config

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/22471976

fix: fix ignore file error cause cannot startup after deploy 

---

todo-list-with-Azure-backend/package.json

Fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23193226

fix: make local debug work for todo sample

---

hello-world-teams-tab-and-outlook-add-in/README.md

Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/21818206
and https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/23284681

docs: fix outdated doc

---

todo-list-SPFx/src/package-lock.json
todo-list-SPFx/src/package.json

This reverts commit 037a60f9ee7b72069283f54ea15213255a941bbd.

Revert "chore(deps): bump debug and @microsoft/sp-build-web (#852)"

---

NPM-search-connector-M365/.webappignore
NPM-search-message-extension-codespaces/.webappignore
adaptive-card-notification/.funcignore
query-org-user-with-message-extension-sso/.webappignore
share-now/bot/.webappignore
stocks-update-notification-bot/.funcignore

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/Compute%20Team/Microsoft%20Teams%20Extensibility/CY23-5.3?workitem=22682022

fix: clear deploy ignore file

---

developer-assist-dashboard/.vscode/tasks.json
developer-assist-dashboard/api/package.json
hello-world-tab-with-backend/.vscode/tasks.json
hello-world-tab-with-backend/api/package.json
team-central-dashboard/.vscode/tasks.json
team-central-dashboard/api/package.json

bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY23-7.1?workitem=24527689

fix: close terminal when stop debug

---

hello-world-teams-tab-and-outlook-add-in/appPackage/manifest.json

Fixes https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24551606

fix: groupchat to groupChat

---

graph-connector-app/infra/azure.bicep
todo-list-with-Azure-backend/infra/teamsFx/function.bicep

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24598880

fix: set authorization policy

---

todo-list-with-Azure-backend-M365/infra/teamsFx/function.bicep

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24598904.

fix: set func authorization policy for todo-m365

---

NPM-search-message-extension-codespaces/teamsapp.local.yml
NPM-search-message-extension-codespaces/teamsapp.yml
basic-blazor-tab-app/BasicBlazorTabApp/teamsapp.local.yml
basic-blazor-tab-app/BasicBlazorTabApp/teamsapp.yml
graph-toolkit-contact-exporter/teamsapp.local.yml
graph-toolkit-contact-exporter/teamsapp.yml
graph-toolkit-one-productivity-hub/teamsapp.local.yml
graph-toolkit-one-productivity-hub/teamsapp.yml
hello-world-bot-with-tab/teamsapp.local.yml
hello-world-bot-with-tab/teamsapp.yml
hello-world-tab-codespaces/teamsapp.local.yml
hello-world-tab-codespaces/teamsapp.yml
hello-world-teams-tab-and-outlook-add-in/teamsapp.local.yml
hello-world-teams-tab-and-outlook-add-in/teamsapp.yml
live-share-dice-roller/teamsapp.local.yml
live-share-dice-roller/teamsapp.yml
notification-codespaces/teamsapp.local.yml
notification-codespaces/teamsapp.yml
stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/teamsapp.local.yml
stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/teamsapp.yml
teams-chef-bot/teamsapp.local.yml
teams-chef-bot/teamsapp.yml

feat: update sample yml schema to 1.1.1 with sampleTag
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24599180

feat: update sample yml schema to 1.1.1 with sampleTag

---

bot-sso/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24688690

fix: fix bot-sso build error

---

teams-chef-bot/package.json

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24451412

chore: upgrade botbuilder-m365 package version

---

graph-connector-bot/package.json

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24721678

fix: upgrade jsonwebtoken to fix vulnerabilities

---

bot-sso/commands/showUserProfile.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24568370
Related PR: https://github.com/OfficeDev/TeamsFx/pull/9484

feat: update bot-sso to use graph sdk

---

developer-assist-dashboard/api/callService/index.ts
team-central-dashboard/api/callGraph/index.ts
team-central-dashboard/api/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24568370
Related PR: https://github.com/OfficeDev/TeamsFx/pull/9484

feat: update dashboard samples to use TokenCredentialProvider

---

command-bot-with-sso/package.json
command-bot-with-sso/src/photoSsoCommandHandler.ts
command-bot-with-sso/src/profileSsoCommandHandler.ts
hello-world-tab-with-backend/api/getUserProfile/index.ts
hello-world-tab-with-backend/api/package.json
query-org-user-with-message-extension-sso/teamsBot.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24568370
Related PR: https://github.com/OfficeDev/TeamsFx/pull/9484

feat: migrate to use TokenCredentialAuthenticationProvider

---

teams-chef-bot/package.json

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24767808

chore: update to @microsoft/teams-ai package

---

teams-chef-bot/src/index.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24833264

fix: teams chef sample failed to preview

---

spfx-productivity-dashboard/src/.vscode/launch.json
spfx-productivity-dashboard/src/.yo-rc.json
spfx-productivity-dashboard/src/README.md
spfx-productivity-dashboard/src/assets/sample.json
spfx-productivity-dashboard/src/config/package-solution.json
spfx-productivity-dashboard/src/config/sass.json
spfx-productivity-dashboard/src/config/serve.json
spfx-productivity-dashboard/src/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24833467

fix: eslint error for legacy spfx version

---

spfx-productivity-dashboard/src/README.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24833093

fix: update spfx productivity dashboard sample readme

---

.config/samples-config-v3.json

feat: add shortId in sample config

---

developer-assist-dashboard/api/callService/index.ts
graph-connector-app/tabs/src/components/sample/CurrentUser.tsx
graph-connector-app/tabs/src/components/sample/Query.tsx
todo-list-with-Azure-backend-M365/tabs/package.json
todo-list-with-Azure-backend-M365/tabs/src/components/Creator.js
todo-list-with-Azure-backend/tabs/package.json
todo-list-with-Azure-backend/tabs/src/components/Creator.js

Related PR: https://github.com/OfficeDev/TeamsFx-Samples/pull/978
Fix the issue: https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/1385

feat: update to use latest graph sdk

---

CONTRIBUTING.md

fix: use uppercase for screenshot name

---

.github/workflows/ci-sample-validation.yml

Detect folder change and run validation tool.

ci: run validation against sample onboarding pull request

---

todo-list-with-Azure-backend-M365/tabs/src/components/Creator.js
todo-list-with-Azure-backend/tabs/src/components/Creator.js

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25228613

fix: fix to-do list samples

---

spfx-productivity-dashboard/README.md

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25226894
Screenshot:

fix: screenshot in spfx productivity dashboard sample is broken

---

todo-list-with-Azure-backend/tabs/src/components/Tab.js

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25228613?src=WorkItemMention&src-action=artifact_link

fix: fix credential

---

graph-toolkit-one-productivity-hub/package.json

[Bug 25396861](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25396861): [Sample] one-productivity-hub localdebug and deploy failed

fix: local debug and deploy failed

---

.github/workflows/ci-sample-validation.yml

Ignore .NET projects and validation tool.

fix: new sample validation

---

developer-assist-dashboard/README.md

To fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25423635

fix: the link issue in the README.md of the developer-assist-dashboard sample

---

spfx-productivity-dashboard/appPackage/manifest.local.json

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25505908

fix: app name under local env exceed limitation

---

graph-connector-bot/adaptiveCards/welcome.json
graph-connector-bot/appPackage/manifest.json

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25240251

fix: the app name is inconsistent

---

adaptive-card-notification/teamsapp.local.yml
developer-assist-dashboard/teamsapp.local.yml
graph-connector-app/teamsapp.local.yml
hello-world-tab-with-backend/teamsapp.local.yml
large-scale-notification/teamsapp.local.yml
share-now/teamsapp.local.yml
stocks-update-notification-bot/teamsapp.local.yml
team-central-dashboard/teamsapp.local.yml
todo-list-with-Azure-backend-M365/teamsapp.local.yml
todo-list-with-Azure-backend/teamsapp.local.yml

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25563995/

fix: upgrade func to support node 20

---

graph-connector-bot/package.json

fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25564446

fix: remove unused @azure/msal-node package

---

.config/samples-config-v3.json

It's used in Teams Toolkit sample gallery.

feat: add filter options in sample config

---

.config/samples-config-v3.json

Onboard 2 samples:
1. https://github.com/OfficeDev/TeamsFx-Samples/issues/1076
2. https://github.com/OfficeDev/TeamsFx-Samples/issues/1077
Fix language options and add "Python" option:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25758146
Effect:

hotfix: onboard python related samples

---

team-central-dashboard/README.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25787707

fix: a link issue in the README file

---

.config/samples-config-v3.json

feat: onboard food catalog sample

---

.config/samples-config-v3.json

Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25798066

fix: string typo

---

.config/samples-config-v3.json
large-scale-notification/assets/sample.json

Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25858571

fix: description of notification bot sample

---

graph-connector-app/infra/azure.bicep

Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25700179

fix: correct WEBSITE_AUTH_AAD_ACL

---

.config/samples-config-v3.json

Related onboarding request: #1101

feat: onboard reddit link unfurling sample

---

.config/samples-config-v3.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25944497

feat: change the featured samples

---

hello-world-tab-with-backend/.vscode/tasks.json
hello-world-tab-with-backend/package.json

bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Germanium/CY24Q1/2Wk/2Wk08%20(Dec%2031%20-%20Jan%2013)?workitem=26242043

fix: fix cli issue in obo template

---

NPM-search-connector-M365/README.md
README_template.md
adaptive-card-notification/README.md
bot-sso-docker/README.md
bot-sso/README.md
command-bot-with-sso/README.md
developer-assist-dashboard/README.md
graph-connector-app/README.md
graph-connector-bot/README.md
graph-toolkit-contact-exporter/README.md
graph-toolkit-one-productivity-hub/README.md
hello-world-bot-with-tab/README.md
hello-world-in-meeting/README.md
hello-world-tab-with-backend/README.md
hello-world-tab-with-backend/api/README.md
hello-world-teams-tab-and-outlook-add-in/README.md
intelligent-data-chart-generator/README.md
live-share-dice-roller/README.md
query-org-user-with-message-extension-sso/README.md
react-retail-dashboard/README.md
share-now/README.md
spfx-productivity-dashboard/README.md
sso-enabled-tab-via-apim-proxy/README.md
stocks-update-notification-bot/README.md
team-central-dashboard/README.md
todo-list-SPFx/README.md
todo-list-with-Azure-backend-M365/README.md
todo-list-with-Azure-backend/README.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26592457

fix: broken aka link

---

hello-world-teams-tab-and-outlook-add-in/tab/src/components/sample/EditCode.tsx

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26660236

fix: sample page content

---

graph-connector-app/README.md
live-share-dice-roller/README.md
react-retail-dashboard/README.md
share-now/README.md
spfx-productivity-dashboard/README.md

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26241571

fix: change word preview

---

.config/samples-config-v3.json

Related PR: https://github.com/OfficeDev/TeamsFx/pull/10908

fix: teams chef bot use external repo

---

react-retail-dashboard/appPackage/manifest.json
react-retail-dashboard/src/package.json
react-retail-dashboard/src/src/components/CurrentInventory/CurrentInventory.tsx
react-retail-dashboard/src/src/components/GlobalCustomerSatisfaction/GlobalCustomerSatisfaction.tsx
react-retail-dashboard/src/src/components/ProductSells/ProductSells.tsx
react-retail-dashboard/src/src/components/ReturnReasons/ReturnReasons.tsx
react-retail-dashboard/src/src/components/ReturnVolumes/ReturnVolumes.tsx
react-retail-dashboard/src/src/components/SingleProduct/SingleProduct.tsx
react-retail-dashboard/src/src/components/TopSellerProduct/TopSellerProduct.tsx
react-retail-dashboard/src/src/webparts/retailDashboard/components/RetailDashboard.tsx
react-retail-dashboard/src/src/webparts/retailHome/components/RetailHome.tsx
react-retail-dashboard/src/src/webparts/retailInventory/components/RetailInventory.tsx

[Bug 27087677](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27087677): update deps version in sample react-retail-dashboard

build: react-retail-dashboard deps update

---

NPM-search-connector-M365/README.md
README_template.md
adaptive-card-notification/README.md
bot-sso/README.md
command-bot-with-sso/README.md
developer-assist-dashboard/README.md
graph-connector-app/README.md
graph-connector-bot/README.md
graph-toolkit-contact-exporter/README.md
graph-toolkit-one-productivity-hub/README.md
hello-world-bot-with-tab/README.md
hello-world-in-meeting/README.md
hello-world-tab-with-backend/README.md
hello-world-tab-with-backend/api/README.md
hello-world-teams-tab-and-outlook-add-in/README.md
live-share-dice-roller/README.md
query-org-user-with-message-extension-sso/README.md
react-retail-dashboard/README.md
share-now/README.md
spfx-productivity-dashboard/README.md
sso-enabled-tab-via-apim-proxy/README.md
stocks-update-notification-bot/README.md
team-central-dashboard/README.md
todo-list-SPFx/README.md
todo-list-with-Azure-backend-M365/README.md
todo-list-with-Azure-backend/README.md

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27130563

fix: cli broken link

---

todo-list-with-Azure-backend-M365/tabs/package.json

Same as #1215
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27230553

fix: downgrade sdk version in todo-m365

---

hello-world-teams-tab-and-outlook-add-in/appPackage/manifest.json

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27231476

fix: update office addin manifest

---

graph-toolkit-contact-exporter/README.md
graph-toolkit-contact-exporter/proxy/README.md
hello-world-tab-with-backend/README.md
hello-world-tab-with-backend/proxy/README.md

Fix: 
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27257867
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27259544

fix(devproxy): update readme

---

developer-assist-dashboard/api/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27248125

fix: update @octokit/core version in package.json

---

.config/samples-config-v3.json

1. Add Capability filter option: Word, Excel.
2. Onboard 6 samples:
#1214
#1216
#1217
#1218
#1219
#1224

feat: onboard WXP samples

---

hello-world-tab-docker/api/Dockerfile
hello-world-tab-docker/docker-compose.yml
hello-world-tab-docker/infra/azure.bicep
hello-world-tab-docker/src/components/sample/AzureFunctions.tsx
hello-world-tab-docker/src/components/sample/EditCode.tsx
hello-world-tab-docker/teamsapp.yml

1. Fix wrong code path in tab page. https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27385890/
2. Fix authentication settings - set default allowed client applications
3. Use correct configuration to enable CORS

fix: fix issues in hello-world-tab-docker sample

---

test-tool-sample-app/.localConfigs.testTool
test-tool-sample-app/.vscode/launch.json
test-tool-sample-app/.vscode/tasks.json
test-tool-sample-app/appPackage/manifest.json
test-tool-sample-app/package.json
test-tool-sample-app/src/adaptiveCards/actionMEFetchTaskCard.json
test-tool-sample-app/src/adaptiveCards/actionMEFetchTaskCard1.json
test-tool-sample-app/src/adaptiveCards/actionMEFetchTaskCard2.json
test-tool-sample-app/src/adaptiveCards/actionMESubmitCard.json
test-tool-sample-app/src/adaptiveCards/actionMESubmitStaticCard.json
test-tool-sample-app/src/adaptiveCards/helpResponse.json
test-tool-sample-app/src/adaptiveCards/linkUnfurlingCard.json
test-tool-sample-app/src/adaptiveCards/npmSearchResultCard.json
test-tool-sample-app/src/adaptiveCards/o365ConnectorCard.json
test-tool-sample-app/src/commands/helpCommandHandler.ts
test-tool-sample-app/src/commands/heroCardCommandHandler.ts
test-tool-sample-app/src/commands/markdownCommandHandler.ts
test-tool-sample-app/src/commands/typingCommandHandler.ts
test-tool-sample-app/src/index.ts
test-tool-sample-app/src/internal/initialize.ts
test-tool-sample-app/src/messageExtension/actionCommands.ts
test-tool-sample-app/src/messageExtension/searchCommands.ts
test-tool-sample-app/src/simpleBot.ts
test-tool-sample-app/teamsapp.testtool.yml

Add sample code logic related to Message Extension.

feat: update test tool sample app

---

.config/samples-config-v3.json

Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27589069

fix: teams-chef-bot version

---

bot-sso-docker/package.json

fix: upgrade dependencies

---

.config/samples-config-v3.json

Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27692336

fix: use latest version of teams chef bot sample

---

hello-world-tab-with-backend/teamsapp.local.yml

bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28014141
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28014148

fix: fix sso tab local debug issue

---

hello-world-tab-with-backend/teamsapp.local.yml

fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28014148

fix: fix bug in sso tab

---

graph-connector-app/tabs/package.json
graph-connector-app/tabs/public/auth-end.html
graph-connector-app/tabs/public/auth-start.html
graph-connector-bot/public/auth-end.html
graph-toolkit-contact-exporter/package.json
graph-toolkit-contact-exporter/public/auth-end.html
graph-toolkit-contact-exporter/public/auth-start.html
graph-toolkit-one-productivity-hub/package.json
graph-toolkit-one-productivity-hub/public/auth-end.html
graph-toolkit-one-productivity-hub/public/auth-start.html
hello-world-in-meeting/package.json
hello-world-tab-codespaces/package.json
hello-world-tab-with-backend/package.json
hello-world-tab-with-backend/public/auth-end.html
hello-world-tab-with-backend/public/auth-start.html
hello-world-teams-tab-and-outlook-add-in/tab/package.json
live-share-dice-roller/package.json
query-org-user-with-message-extension-sso/public/auth-end.html
share-now/tabs/package.json
sso-enabled-tab-via-apim-proxy/package.json
sso-enabled-tab-via-apim-proxy/public/auth-end.html
sso-enabled-tab-via-apim-proxy/public/auth-start.html
todo-list-with-Azure-backend-M365/tabs/package.json
todo-list-with-Azure-backend-M365/tabs/public/auth-end.html
todo-list-with-Azure-backend-M365/tabs/public/auth-start.html
todo-list-with-Azure-backend/tabs/package.json
todo-list-with-Azure-backend/tabs/public/auth-end.html
todo-list-with-Azure-backend/tabs/public/auth-start.html
whos-next-meeting-app/tabs/package.json

feature: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27300222
sample upgrade form: https://microsoft.sharepoint.com/:fl:/s/0c4fbe93-3f50-4ee2-aabb-9d812c3b03db/ETPgsjNVQINIlHBIcRHj2iQByYOM6rf9452B3CWE1TAqnQ?e=8qidGA&nav=cz0lMkZzaXRlcyUyRjBjNGZiZTkzLTNmNTAtNGVlMi1hYWJiLTlkODEyYzNiMDNkYiZkPWIheXVvVUYwZGQtMDZJX1g2U2w1dVhBRUNMN3JhU01hNUZsU19vT3Z6UUJBUDdaMG1fUEZJZVI2cHR1NzhOb1ZwUSZmPTAxSDNMWlhLWlQ0Q1pER1ZLQVFORUpJNENJT0VJNkhXUkUmYz0lMkYmZmx1aWQ9MSZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUY1ZFc5VlJqQmtaQzB3TmtsZldEWlRiRFYxV0VGRlEwdzNjbUZUVFdFMVJteFRYMjlQZG5wUlFrRlFOMW93YlY5UVJrbGxValp3ZEhVM09FNXZWbkJSZkRBeFNETk1XbGhMTmtWT01rRkVXRTVOVjBwQ1JWcFdSa0pPUVRkTFVWQlVXV …

build: upgrade teams-js

---

large-scale-notification/appPackage/manifest.json
large-scale-notification/teamsapp.local.yml
large-scale-notification/teamsapp.yml

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28240075

build: Update teamsapp.yml

---

intelligent-data-chart-generator/appPackage/manifest.json
intelligent-data-chart-generator/teamsapp.local.yml
intelligent-data-chart-generator/teamsapp.yml
test-tool-sample-app/appPackage/manifest.json
test-tool-sample-app/teamsapp.local.yml
test-tool-sample-app/teamsapp.yml

fix: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28176468

fix: app name pattern

---

developer-assist-dashboard/appPackage/manifest.json
developer-assist-dashboard/infra/azure.bicep
developer-assist-dashboard/teamsapp.local.yml
hello-world-bot-with-tab/appPackage/manifest.json
hello-world-bot-with-tab/infra/azure.bicep
hello-world-bot-with-tab/teamsapp.local.yml
hello-world-in-meeting/appPackage/manifest.json
hello-world-in-meeting/infra/azure.bicep
hello-world-in-meeting/teamsapp.local.yml
team-central-dashboard/appPackage/manifest.json
team-central-dashboard/infra/azure.bicep
team-central-dashboard/teamsapp.local.yml

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28329662/

fix: add a new env variable for the tab valid domain

---

.devcontainer/hello-world-tab-codespaces/devcontainer.json
.devcontainer/notification-codespaces/devcontainer.json
.devcontainer/npm-search-message-extension-codespaces/devcontainer.json

Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28373244

fix: repo rename in codespace devcontainer.json

---

sso-enabled-tab-via-apim-proxy/infra/azure.parameters.json
team-central-dashboard/infra/azure.parameters.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28763279

fix: fix swa sku parameter

---

sso-enabled-tab-via-apim-proxy/infra/azure.parameters.json
sso-enabled-tab-via-apim-proxy/infra/provision.bicep
team-central-dashboard/infra/azure.parameters.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28763279

fix: fix sku parameter error for SWA

---

large-scale-notification/infra/azure.bicep

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28791888

fix: rollback storage usage in extra data store

---

.config/samples-config-v3.json

feat: onboard graph rsc sample

---

bot-sso-docker/infra/azure.bicep
bot-sso-docker/infra/azure.parameters.json
bot-sso-docker/infra/botRegistration/azurebot.bicep
bot-sso-docker/src/config.ts
bot-sso-docker/src/index.ts
bot-sso-docker/teamsapp.local.yml
bot-sso-docker/teamsapp.yml
bot-sso/infra/azure.bicep
bot-sso/infra/azure.parameters.json
bot-sso/infra/botRegistration/azurebot.bicep
bot-sso/src/config.ts
bot-sso/src/index.ts
bot-sso/teamsapp.local.yml
bot-sso/teamsapp.yml

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28807676

feat: update bot-sso and bot-sso-docker to msi

---

share-now/bot/index.ts
share-now/env/.env.dev.user
share-now/infra/azure.parameters.json
share-now/infra/provision.bicep
share-now/infra/provision/bot.bicep
share-now/infra/teamsFx/bot.bicep
share-now/teamsapp.local.yml
share-now/teamsapp.yml

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28807676

update share-now to use msi for remote

---

graph-connector-bot/helpers/utils.ts
large-scale-notification/src/functions/sendNotificationQueueTrigger.ts
share-now/infra/main.bicep

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28939022/

fix: fix sample errors

---

share-now/api/tsconfig.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29260237

fix: build error

---

hello-world-tab-with-backend/api/tsconfig.json

[Bug 29260214](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29260214): [AUTOBUG] e2e - Sample Tests: hello-world-tab-with-backend failed - 15277459

fix: hello-world-tab-with-backend deploy issue

---

hello-world-tab-docker/api/tsconfig.json

BUG: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29256520

fix: fix hello-world-tab-docker

---

notification-codespaces/src/index.js

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29332479

fix: fix adaptive card msg

---

graph-connector-bot/services/utils.ts

fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29361365

fix(graph-connector-bot): fix import issue

---

hello-world-teams-tab-and-outlook-add-in/.vscode/tasks.json
hello-world-teams-tab-and-outlook-add-in/add-in/package-lock.json
hello-world-teams-tab-and-outlook-add-in/package-lock.json
hello-world-teams-tab-and-outlook-add-in/tab/index.html
hello-world-teams-tab-and-outlook-add-in/tab/package-lock.json
hello-world-teams-tab-and-outlook-add-in/tab/package.json
hello-world-teams-tab-and-outlook-add-in/tab/tsconfig.app.json
hello-world-teams-tab-and-outlook-add-in/tab/tsconfig.json
hello-world-teams-tab-and-outlook-add-in/tab/tsconfig.node.json
hello-world-teams-tab-and-outlook-add-in/tab/vite.config.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29629221

fix: migrate tab add-in sample to vite

---

adaptive-card-notification/package.json
bot-sso-docker/package.json
bot-sso/package.json
large-scale-notification/package.json
query-org-user-with-message-extension-sso/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29642492

fix: fix bot sample build error

---

hello-world-tab-with-backend/api/tsconfig.json

fix bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29666256

fix: fix obo template

---

graph-connector-app/api/tsconfig.json
graph-connector-bot/package.json

fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29665542

fix: fix build error

---

share-now/api/tsconfig.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29665581

fix: build error for sharenow

---

hello-world-teams-tab-and-outlook-add-in/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29808405

fix: postbuild script for tab and addin sample

---

share-now/api/package.json
share-now/api/tsconfig.json
share-now/bot/package.json
share-now/bot/tsconfig.json

e2e: https://github.com/OfficeDev/teams-toolkit/actions/runs/11265662101/job/31328209499

fix: build error for share now

---

hello-world-teams-tab-and-outlook-add-in/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30159977

fix: postbuild for tab and outlook add-in sample

---

hello-world-teams-tab-and-outlook-add-in/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30149297

fix(hotfix): outlook add-in and tab postbuild script

---

hello-world-teams-tab-and-outlook-add-in/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30297359

fix: postbuild for outlook add-in sample

---

hello-world-bot-with-tab/tab/vite.config.ts
hello-world-teams-tab-and-outlook-add-in/tab/vite.config.ts
intelligent-data-chart-generator/vite.config.ts
team-central-dashboard/vite.config.ts

BUG: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30354886
Related BUG: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30341980

fix: add global definition in vite config

---

hello-world-bot-with-tab/tab/vite.config.ts
hello-world-teams-tab-and-outlook-add-in/tab/vite.config.ts
intelligent-data-chart-generator/vite.config.ts
team-central-dashboard/vite.config.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30354886

fix: fix global definition in vite config

---

test-tool-sample-app/src/index.ts
test-tool-sample-app/src/internal/initialize.ts

fix issue: https://github.com/OfficeDev/teams-toolkit-samples/issues/1398

fix: update code to fit library updates

---

.config/samples-config-v3.json

bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30522690?src=WorkItemMention&src-action=artifact_link

fix: remove live code sample as it could not be fixed

---

templates/command-and-response-js/README.md
templates/default-bot-js/README.md
templates/message-extension-action-js/README.md
templates/workflow-ts/README.md

chore: update test tool screenshots

---

.config/samples-config-v3.json
copilot-connector-app/README.md
copilot-connector-app/api/src/functions/connection.ts
copilot-connector-app/assets/sample.json
copilot-connector-app/tabs/src/components/sample/Ingest.tsx
copilot-connector-app/tabs/src/components/sample/Introduce.tsx
copilot-connector-app/tabs/src/components/sample/Query.tsx
copilot-connector-app/tabs/src/components/sample/Welcome.tsx
copilot-connector-bot/README.md
copilot-connector-bot/adaptiveCards/welcome.json
copilot-connector-bot/appPackage/manifest.json
copilot-connector-bot/assets/sample.json
copilot-connector-bot/commands/query.ts
copilot-connector-bot/services/constants.ts
templates/copilot-rag-m365/.tours/load-data-from-graph-connector.tour
templates/copilot-rag-m365/README.md

refactor: update

---

hello-world-office-addin/README.md

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/32837050/

docs: fix hello world office add-in readme link

---

.config/samples-config-v3.json

Revert #1420 because external samples have rebranded.

Revert "fix: temporarily remove external samples until they are updated"

---

spfx-productivity-dashboard/src/.eslintrc.js
todo-list-SPFx/src/.eslintrc.js

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33255842/?view=edit

fix: remove eslint rules to fix e2e

---

hello-world-teams-tab-and-outlook-add-in/m365agents.yml
live-share-dice-roller/m365agents.yml
react-retail-dashboard/README.md
react-retail-dashboard/appPackage/manifest.local.json
react-retail-dashboard/package.json
react-retail-dashboard/src/.eslintrc.js
react-retail-dashboard/src/.yo-rc.json
react-retail-dashboard/src/package.json
react-retail-dashboard/src/tsconfig.json

ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33409009/?view=edit
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33409078/?view=edit

fix: yml parse error in samples

---

adaptive-card-notification/package.json
large-scale-notification/package.json

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33539237
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33539237
Need adaptivecards package as well:
https://github.com/microsoft/AdaptiveCards/issues/8676

fix: add adaptivecards dependency

---

graph-toolkit-one-productivity-hub/m365agents.yml

[Bug 33757727](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33757727): [AUTOBUG] e2e - Sample Tests: graph-toolkit-one-productivity-hub failed - 15277463

fix: e2e test failed

---

graph-toolkit-one-productivity-hub/src/components/lib/useTeams.js

[Bug 33757727](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33757727): [AUTOBUG] e2e - Sample Tests: graph-toolkit-one-productivity-hub failed - 15277463
https://github.com/OfficeDev/microsoft-365-agents-toolkit/actions/runs/16460944524/job/46528102027#step:23:417
e2e test result:
https://github.com/OfficeDev/microsoft-365-agents-toolkit/actions/runs/16462390632

fix(lint): react hook useEffect has missing dependencies

---

.config/samples-config-v3.json

Onboarding request: https://github.com/OfficeDev/microsoft-365-agents-toolkit-samples/issues/1462

feat: onboard new cea sample

---

copilot-connector-app/tabs/package.json
copilot-connector-app/tabs/src/components/sample/lib/useData.ts
copilot-connector-app/tabs/src/components/sample/lib/useTeams.ts

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33822002
Related: https://github.com/OfficeDev/microsoft-365-agents-toolkit-samples/pull/1467
E2E test passed: https://github.com/OfficeDev/microsoft-365-agents-toolkit/actions/runs/16513309974

fix: add missing dependency

---

developer-assist-dashboard/src/lib/useTeams.ts

bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/Bromine/CY25Q3/2Wk/2Wk08%20(Jul%2013%20-%20Jul%2026)?workitem=33821482

fix(test): fix bulid warning to fix e2e test

---

.config/samples-config-v3.json

bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/34965062/

fix: external sample link

---

.config/samples-config-v3.json

fix: sample link
