OfficeDev/microsoft-365-agents-toolkit-samples

- share-now/.vscode/launch.json
- todo-list-with-Azure-backend/.vscode/launch.json
Add `&webjoin=true` to launch url to **skip** the selector page:
> fix: skip join view when local debug

- in-meeting-app/bot/package.json
BUG https://dev.azure.com/msazure/Microsoft%20Teams%20Extensibility/_workitems/edit/9978317
CROSS-ENV command not found in WSL, change to cross-env to fix it.
> Update in-meeting app to fix the 'npm start' bug on WSL

- share-now/tabs/package.json
Will revoke the change after we resolve the bug in Teams Toolkit.
> fix(share-now): workaround dependency conflict issue

- hello-world-tab-with-backend/README.md
- hello-world-tab-with-backend/tabs/src/components/sample/lib/useGraph.ts
- hello-world-tab/README.md
- hello-world-tab/tabs/src/components/sample/lib/useGraph.ts
@zhenyasav , could you help provide the helper link target URL, I will update it in aka service: https://aka.ms/teamsfx-session-storage-notice
Related task:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_sprints/taskboard/AuthAndData/Microsoft%20Teams%20Extensibility/CY21-12.1?workitem=12699312
> docs: add session storage notice

- bot-sso/.fx/configs/projectSettings.json
This property is added for telemetry to distinguish whether current event is from sample or scratch projects.
> fix: add missing isFromSample property for telemetry

- hello-world-tab-with-backend/api/package.json
- hello-world-tab-with-backend/tabs/package.json
- hello-world-tab/tabs/package.json
- todo-list-with-Azure-backend-M365/api/package.json
- todo-list-with-Azure-backend-M365/tabs/package.json
- todo-list-with-Azure-backend/api/package.json
- todo-list-with-Azure-backend/tabs/package.json
Since currently @microsoft/teamsfx v0.5.0 has not yet been released and thus the sample using 0.5.0 will be broken, change the sdk version to v0.5.0-rc so the sample in dev branch is workable.
Consider change sdk version back to 0.5.0 after 0.5.0 release (after Feb. 7th).
> perf: update sdk version to 0.5.0-rc

- todo-list-with-Azure-backend-M365/tabs/package.json
The M365 sample should use next(tag) teamsfx sdk to not only work on Teams.
> fix(M365): use latest next teamsfx sdk to work on outlook/office

- .github/workflows/codeql-analysis.yml
now 
windows-latest not windows-2019, is windows-2022, the page display error. 
https://github.com/actions/virtual-environments/issues/4856
VS in windows-2019 is VS 2019, and windows-2022 is VS-2022.
codeSQL not supported in VS 2022, but success on 2019. 
https://github.com/m4rs-mt/ILGPU/pull/761
> chore: upgrade the codeQL version

- adaptive-card-notification/README.md
- adaptive-card-notification/bot/package.json
- adaptive-card-notification/bot/src/internal/initialize.ts
- adaptive-card-notification/bot/src/storage/blobsStorage.ts
This adds a sample implementation of `NotificationTargetStorage` to persist to Azure Blob Storage.
Since we haven't provided such implementation from our SDK, this is the sample that we can provide to developers to try Azure Blob Storage for production environments.
> feat: add notification storage implemenation sample

- NPM-search-connector-M365/README.md
- faq-plus/configapp/Microsoft.Teams.Apps.FAQPlusPlus.Common/Providers/IKnowledgeBaseSearchService.cs
- faq-plus/configapp/Microsoft.Teams.Apps.FAQPlusPlus.Common/Providers/KnowledgeBaseSearchService.cs
- faq-plus/configapp/Microsoft.Teams.Apps.FAQPlusPlus.Common/Providers/SearchService.cs
- faq-plus/configapp/Microsoft.Teams.Apps.FAQPlusPlus.Common/Providers/TicketsProvider.cs
- share-now/README.md
Update naming for samples
Still need to sync with Teams team about the interface which contains the naming 'messaging extension'
Like 'handleTeamsMessagingExtensionQuery'
> chore: rename messaging extension to message extension

- hello-world-tab-with-backend/tabs/package.json
- hello-world-tab/tabs/package.json
msteams-react-base-component is a peer dependency of @microsoft/teamsfx-react. npm@6 does not install peer dependency so these sample may fail to build with npm@6.
> fix: support npm lower than 6

- share-now/api/extensions.csproj
- share-now/tabs/.eslintrc
- share-now/tabs/package.json
1. support node 14 and fix tab npm run build error
2. modify the api pkg to the function 1.0.0 stable version
> chore: change the pkg to a release pkg

- graph-connector-app/.vscode/launch.json
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14524997
> fix(graph-connector): 'Attach to Backend' does not stop after closing browser in local debug

- NPM-search-connector-M365/.fx/configs/azure.parameters.dev.json
Seems that there is some error on the merge from ga/release to dev before, so let me add the resource name suffix again.
The change for todo-list-with-Azure-backend-M365 is in https://github.com/OfficeDev/TeamsFx-Samples/pull/431.
> chore(m365): add resource name suffix

- graph-connector-app/README.md
- graph-connector-app/api/data/index.ts
- graph-connector-app/api/schema/index.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/14938222
This issue is caused by a regression in Graph Connector. 'double' type in schema would be affected if you are using JS. See more in https://o365exchange.visualstudio.com/defaultcollection/O365%20Core/_workitems/edit/2931419
For quick workaround, update 'double' type to 'string' type.
> fix(graph-connector): workaround fix to update 'double' type to 'string'

- graph-connector-app/api/data/index.ts
- graph-connector-app/api/schema/index.ts
Graph Connector server side has fixed the issue, so rollback our workaround: https://github.com/OfficeDev/TeamsFx-Samples/pull/439
> fix(graph-connector): rollback the workaround fix

- graph-toolkit-one-productivity-hub/.fx/configs/azure.parameters.dev.json
- graph-toolkit-one-productivity-hub/README.md
fix: wrong link in README.md(code of conduct: public)
fix: change fixed resource name suffix to dynamic in .fx/azure.parameters.dev.json
> Fix a bad link and parameters for one productivity hub

- graph-connector-app/README.md
- graph-connector-app/api/connection/index.ts
- graph-connector-app/tabs/src/components/sample/Ingest.tsx
- graph-connector-app/templates/appPackage/aad.template.json
Updating permissions for Azure AD consent of Graph connector app to use more fine-grained ".OwnedBy" versions instead of ".All".
> Update AAD permissions consented to app

- todo-list-with-Azure-backend/tabs/src/components/Tab.js
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/10076341
When click on item 15,
Before:
After:
> fix(todo on azure): fix position of delete button

- adaptive-card-notification/bot/package.json
TeamsFx SDK depends on botbuilder: >=4.15.0<5.0.0, while the latest version of botbuilder is 4.17.0. Those bot templates depend on ~4.15.0 will face the compile error caused by the unmatched version.
Therefore, update the affected samples' package.json to sync the version with SDK.
```
node_modules/@microsoft/teamsfx/types/teamsfx.d.ts:424:15 - error TS2416: Property 'onEndDialog' in type 'BotSsoExecutionDialog' is not assignable to the same property in base type 'ComponentDialog<{}>'.
Type '(context: TurnContext) => Promise<void>' is not assignable to type '(_context: TurnContext, _instance: DialogInstance<any>, _reason: DialogReason) => Promise<void>'.
Types of parameters 'context' and '_context' are incompatible.
Type 'import("<path>/bot/node_modules/botbuilder-dialogs/node_modules/botb …
```
> fix: sync botbuilder version with SDK

- hello-world-bot/bot/teamsBot.ts
Use DataInterface to make it clear to readers that `likeCountObj` is an object of `interface DataInterface`
> Use DataInterface to make it easier for readers to understand

- stocks-update-notification-bot/bot/src/timerTrigger.ts
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15580856/
`sendAdaptiveCard` may return `void` or `MessageResponse`, depending on SDK version. So use `any` to keep compatibility.
> fix: fix type error

- faq-plus/README.md
Because QnA Maker is being retired: https://azure.microsoft.com/en-us/updates/azure-qna-maker-will-be-retired-on-31-march-2025/
> chore: deprecate FAQ Plus sample

- graph-toolkit-productivity-hub-aspnetcore/OneProductivityHubAspNetCore/Pages/_Host.cshtml
Pins Microsoft Graph Toolkit CDN reference to v2 to avoid breaking sample when v3 will be released later this year.
> Pins MGT to v2

- graph-connector-app/README.md
- graph-connector-app/api/connection/index.ts
- graph-connector-app/tabs/src/components/sample/Ingest.tsx
- graph-connector-app/templates/appPackage/aad.template.json
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16125030
When trying to ingest data into a connector created by another app, 'ExternalItem.ReadWrite.OwnedBy' is not enough. So use 'ExternalItem.ReadWrite.All'.
> fix(graph-connector): use right permission

- bot-sso/package.json
- command-bot-with-sso/bot/package.json
- graph-connector-bot/bot/package.json
- hello-world-bot-with-tab/bot/package.json
- hello-world-bot/package.json
- query-org-user-with-message-extension-sso/bot/package.json
- share-now/bot/package.json
(This is for v3 branch)
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/16598471/
https://github.com/restify/node-restify/releases/tag/v10.0.0
Update all bot samples to use `restify:10` which supports node 18.
> chore: (v3) upgrade restify to support node 18

- adaptive-card-notification/appPackage/manifest.template.json
- adaptive-card-notification/teamsfx/app.local.yml
- adaptive-card-notification/teamsfx/app.yml
- bot-sso/appPackage/manifest.template.json
- bot-sso/teamsfx/app.local.yml
- bot-sso/teamsfx/app.yml
- hello-world-bot-with-tab/appPackage/manifest.template.json
- hello-world-in-meeting/appPackage/manifest.template.json
- hello-world-in-meeting/teamsfx/app.local.yml
- hello-world-in-meeting/teamsfx/app.yml
- hello-world-tab-with-backend/appPackage/manifest.template.json
- hello-world-tab-with-backend/teamsfx/app.local.yml
- hello-world-tab-with-backend/teamsfx/app.yml
- query-org-user-with-message-extension-sso/appPackage/manifest.template.json
- query-org-user-with-message-extension-sso/teamsfx/app.local.yml
- query-org-user-with-message-extension-sso/teamsfx/app.yml
- stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/appPackage/manifest.template.json
- stocks-update-notification-bot/appPackage/manifest.template.json
- stocks-update-notification-bot/teamsfx/app.local.yml
- stocks-update-notification-bot/teamsfx/app.yml
- todo-list-SPFx/appPackage/manifest.template.json
- todo-list-SPFx/appPackage/manifest.template.local.json
- todo-list-SPFx/teamsfx/app.local.yml
- todo-list-SPFx/teamsfx/app.yml
For samples, will use static name with ${{TEAMSFX_ENV}} suffix to differentiate local /dev app name.
> chore: remove TEAMS_APP_NAME env

- todo-list-with-Azure-backend-M365/teamsapp.local.yml
- todo-list-with-Azure-backend-M365/teamsapp.yml
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17337112.
> chore(v3): add execPath for cli/runDotnetCommand in todo m365

- adaptive-card-notification/appPackage/manifest.json
- stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/appPackage/manifest.json
- stocks-update-notification-bot/appPackage/manifest.json
detail: 
Xiaofu Huang[(P2) [adaptive-card-notification] check if "validDomain" in manifest can be removed](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17304210)
Xiaofu Huang[(P2) [stock-update-notification-bot-dotnet] check if "validDomain" in manifest can be removed](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17304470)
Xiaofu Huang[(P2) [stocks-update-notification-bot] check if "validDomain" in manifest can be removed](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17304480)
> chore: remove botDomain in validDomains

- query-org-user-with-message-extension-sso/teamsBot.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17470758
User may not set personal photo, and get photo may failed, so to update the logic to return the result without photo if not exist.
> fix: fix the photo error once user doese not have

- hello-world-teams-tab-and-outlook-add-in/README.md
- hello-world-teams-tab-and-outlook-add-in/add-in/webpack.config.js
- hello-world-teams-tab-and-outlook-add-in/teamsapp.local.yml
- hello-world-teams-tab-and-outlook-add-in/teamsapp.yml
For p0 bug:
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17885411
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17900028
1) Update default path in webpack.config.js as the build output path has been changed from `./build/appPackage` to `./appPackage/build`
2) Update yml with writeToEnvironmentFile
3) Remove teamsApp/validateAppPackage from yml, as office-add in app uses another manifest schema. The server side doesn't accept "extensions" field.
> fix: update yml and webpack for office add-in samples

- hello-world-in-meeting/README.md
It seems there's some changes related to the former link, so update the link with the new one to redirect developers to the app caching section.
> chore: update the link to app caching's section

- developer-assist-dashboard/teamsapp.local.yml
- graph-connector-app/teamsapp.local.yml
- graph-toolkit-contact-exporter/teamsapp.local.yml
- graph-toolkit-one-productivity-hub/teamsapp.local.yml
- hello-world-bot-with-tab/teamsapp.local.yml
- hello-world-in-meeting/teamsapp.local.yml
- hello-world-tab-codespaces/teamsapp.local.yml
- hello-world-tab-with-backend/teamsapp.local.yml
- hello-world-teams-tab-and-outlook-add-in/teamsapp.local.yml
- share-now/teamsapp.local.yml
- team-central-dashboard/teamsapp.local.yml
- todo-list-with-Azure-backend-M365/teamsapp.local.yml
- todo-list-with-Azure-backend/teamsapp.local.yml
Fix https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17884838/
Merge multiple `::set-teamsfx-env` to one action to make template clearer.
The semicolon(`;`) works as separator in both pwsh and bash which are the default shell of script action.
> fix: set env better format

- adaptive-card-notification/.funcignore
- adaptive-card-notification/.gitignore
- adaptive-card-notification/.vscode/tasks.json
- adaptive-card-notification/teamsapp.local.yml
- share-now/.gitignore
- share-now/.vscode/tasks.json
- share-now/teamsapp.local.yml
- stocks-update-notification-bot/.funcignore
- stocks-update-notification-bot/.gitignore
- stocks-update-notification-bot/.vscode/tasks.json
- stocks-update-notification-bot/teamsapp.local.yml
- todo-list-with-Azure-backend-M365/.gitignore
- todo-list-with-Azure-backend-M365/.vscode/tasks.json
- todo-list-with-Azure-backend-M365/teamsapp.local.yml
- todo-list-with-Azure-backend/.gitignore
- todo-list-with-Azure-backend/.vscode/tasks.json
- todo-list-with-Azure-backend/teamsapp.local.yml
Detail:
[Bug 17943760](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17943760): [V3] Replace "command:get-func-path" with soft link after support versioning installation
[Bug 17920588](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17920588): [V3] Support versioning install
Related to PR: https://github.com/OfficeDev/TeamsFx/pull/8482
> fix: update samples to support versioning func installation

- deep-linking-hello-world-tab-without-sso-M365/README.md
- whos-next-meeting-app/README.md
Revert the changes in https://github.com/OfficeDev/TeamsFx-Samples/pull/868. These samples are not support in V5.
> docs: revert ttk version change for non-v5 sample

- NPM-search-message-extension-codespaces/README.md
- hello-world-tab-codespaces/README.md
- notification-codespaces/README.md
In codespaces sample readme, when user click the `Open in GitHub Codespaces` badge, the default branch in creation page should be `v3`:
> docs: update codespaces creation link to use v3 branch

- NPM-search-message-extension-codespaces/README.md
- hello-world-tab-codespaces/README.md
- notification-codespaces/README.md
Per feedback from Codespaces team, we can add `resume=1` to the `Open in GitHub Codespaces` badge. This will simplify the creation flow for users, and if they already have a Codespace from that repo and branch it'll prompt them to reuse their codespace instead of just creating a new codespace any single time.
> docs: support resume codespace if it already exists

- .github/workflows/cd.yml
if not set v3 as release branch, will not push the new tag to repo
https://github.com/OfficeDev/TeamsFx-Samples/actions/runs/4955218556
once set, can push to repo
> chore: set v3 as release branch

- .config/samples-config-v3.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24598028?src=WorkItemMention&src-action=artifact_link
> fix: TTK is downloading sample from wrong tag url

- .config/samples-config-v3.json
This reverts commit 94a8714455b2fc5080b480acf37dcb3202c4ccd6.
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24610557
> fix: Revert "fix: TTK is downloading sample from wrong tag url"

- NPM-search-connector-M365/.vscode/extensions.json
- NPM-search-message-extension-codespaces/.vscode/extensions.json
- adaptive-card-notification/.vscode/extensions.json
- bot-sso/.vscode/extensions.json
- command-bot-with-sso/.vscode/extensions.json
- developer-assist-dashboard/.vscode/extensions.json
- graph-connector-app/.vscode/extensions.json
- graph-connector-bot/.vscode/extensions.json
- graph-toolkit-contact-exporter/.vscode/extensions.json
- graph-toolkit-one-productivity-hub/.vscode/extensions.json
- hello-world-bot-with-tab/.vscode/extensions.json
- hello-world-in-meeting/.vscode/extensions.json
- hello-world-tab-codespaces/.vscode/extensions.json
- hello-world-tab-with-backend/.vscode/extensions.json
- hello-world-teams-tab-and-outlook-add-in/.vscode/extensions.json
- incoming-webhook-notification/.vscode/extensions.json
- live-share-dice-roller/.vscode/extensions.json
- notification-codespaces/.vscode/extensions.json
- query-org-user-with-message-extension-sso/.vscode/extensions.json
- share-now/.vscode/extensions.json
- stocks-update-notification-bot/.vscode/extensions.json
- team-central-dashboard/.vscode/extensions.json
- teams-chef-bot/.vscode/extensions.json
- todo-list-SPFx/.vscode/extensions.json
- todo-list-with-Azure-backend-M365/.vscode/extensions.json
- todo-list-with-Azure-backend/.vscode/extensions.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/15649538/
When a user who has not installed TTK attempts to open a project created by TTK, we would like for them to receive the following notification from VS Code:
> feat: add TTK to recommended extension list for samples

- graph-connector-app/api/connection/index.ts
- graph-connector-app/api/data/index.ts
- graph-connector-app/api/schema/index.ts
- graph-connector-app/api/status/index.ts
- graph-connector-bot/services/graphQueryService.ts
- graph-connector-bot/services/graphService.ts
- todo-list-with-Azure-backend-M365/tabs/package.json
- todo-list-with-Azure-backend/tabs/package.json
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24568370
Related PR: https://github.com/OfficeDev/TeamsFx/pull/9484
Fix the version of TeamsFx package in two todo-list samples due to the following warning during compilation. Only these two samples show the error and other samples and templates work fine.
> feat: migrate to use TokenAuthenticationProvider and fix some samples to certain teamsfx version

- live-share-dice-roller/.vscode/launch.json
- live-share-dice-roller/.vscode/tasks.json
Received reports of http server not being closed when stopping, which prevents relaunching from working due to port 3000 already being used. PR ensures that all resources are closed when stopping the task.
https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/3261265
> Live-share-dice-roller: Ensure all resources are closed when stopping a task

- live-share-dice-roller/appPackage/manifest.json
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24833504
> fix: no add to meeting button for live share sample

- developer-assist-dashboard/assets/sample.json
Add a Metadata file for onboarding Teams Toolkit samples in [Microsoft 365 Sample Solution Gallery](https://adoption.microsoft.com/en-us/sample-solution-gallery/).
> add metadata for dev assist dashboard sample

- .github/ISSUE_TEMPLATE/new-sample-onboard-request.md
> docs: add onboarding request template

- react-retail-dashboard/src/src/components/ProductsOnLaunch/ProductsOnLaunch.tsx
ADO: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/25106636
Root cause: https://stackoverflow.com/questions/55550096/ts2322-type-timeout-is-not-assignable-to-type-number-when-running-unit-te
> fix: type mismatch issue

- .config/samples-config-v3.json
Related PR: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/960
> fix: thumbnail path for external sample

- .config/samples-config-v3.json
- NPM-search-connector-M365/README.md
- adaptive-card-notification/README.md
- basic-blazor-tab-app/README.md
- bot-sso/README.md
- developer-assist-dashboard/README.md
- graph-connector-app/README.md
- graph-connector-bot/README.md
- graph-toolkit-contact-exporter/README.md
- graph-toolkit-one-productivity-hub/README.md
- hello-world-in-meeting/README.md
- hello-world-tab-with-backend/README.md
- hello-world-teams-tab-and-outlook-add-in/README.md
- incoming-webhook-notification/README.md
- large-scale-notification/README.md
- large-scale-notification/assets/sample.json
- live-share-dice-roller/README.md
- query-org-user-with-message-extension-sso/README.md
- share-now/README.md
- sso-enabled-tab-via-apim-proxy/README.md
- stocks-update-notification-bot-dotnet/README.md
- stocks-update-notification-bot/README.md
- team-central-dashboard/README.md
- teams-chef-bot/README.md
- todo-list-SPFx/README.md
- todo-list-with-Azure-backend-M365/README.md
- todo-list-with-Azure-backend/README.md
The YAML front-matter is used to show in MS learn samples.
Related doc: https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main&branchFallbackFrom=master
Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26002435
> feat: add metadata to readme

- graph-toolkit-contact-exporter/src/components/Tab.js
[Bug 26020915](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/26020915): [vsc] sample "connector exporter" placeholder text display incomplete
This is a bug of graph toolkit: https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/2915
> fix: people picker placeholder was not fully displayed

- .config/samples-config-v3.json
Related PR: https://github.com/microsoft/teams-ai/pull/1354
> fix: teams chef bot use latest thumbnail

- graph-toolkit-contact-exporter/package.json
- graph-toolkit-one-productivity-hub/package.json
[Bug 27164073](https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27164073): @microsoft/teamsfx@2.3.1 caused sample contact-exporter and one-productivity-hub failed
> fix: login not work issue due to axios version conflict

- .config/samples-config-v3.json
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27192466
> fix: teams-chef-bot thumbnail path

- .config/samples-config-v3.json
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/27355478
> fix: add 'dev proxy' tag to sample and filter

- .config/samples-config-v3.json
> feat: onboard hello-world-tab-docker

- adaptive-card-notification/infra/azure.bicep
- adaptive-card-notification/infra/azure.parameters.json
- developer-assist-dashboard/infra/azure.bicep
- developer-assist-dashboard/infra/azure.parameters.json
- graph-connector-app/infra/azure.bicep
- graph-connector-app/infra/azure.parameters.json
- hello-world-tab-with-backend/infra/azure.bicep
- hello-world-tab-with-backend/infra/azure.parameters.json
- intelligent-data-chart-generator/infra/azure.bicep
- intelligent-data-chart-generator/infra/azure.parameters.json
- large-scale-notification/infra/azure.bicep
- share-now/infra/provision/function.bicep
- stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/infra/azure.bicep
- stocks-update-notification-bot-dotnet/StocksUpdateNotificationBot/infra/azure.parameters.json
- stocks-update-notification-bot/infra/azure.bicep
- stocks-update-notification-bot/infra/azure.parameters.json
- team-central-dashboard/infra/azure.bicep
- team-central-dashboard/infra/azure.parameters.json
- todo-list-with-Azure-backend-M365/infra/provision/function.bicep
- todo-list-with-Azure-backend/infra/provision/function.bicep
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28665063/?view=edit
> feat: simplify function creation

- adaptive-card-notification/package.json
- adaptive-card-notification/src/store/blobStore.ts
As a sample implementation of conversation reference store, secure `blobStore` to support MSI as well.
> fix: support MSI for blob store

- .config/samples-config-v3.json
Related bug: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/29016018
Effect:
> fix: sample image path

- NPM-search-message-extension-codespaces/package.json
- adaptive-card-notification/package.json
- adaptive-card-notification/src/columnsetNotificationHttpTrigger.ts
- adaptive-card-notification/src/defaultNotificationHttpTrigger.ts
- adaptive-card-notification/src/factsetNotificationHttpTrigger.ts
- adaptive-card-notification/src/listNotificationHttpTrigger.ts
- adaptive-card-notification/src/mentionNotificationHttpTrigger.ts
- hello-world-bot-with-tab/bot/package.json
- hello-world-bot-with-tab/bot/teamsBot.ts
- incoming-webhook-notification/package.json
- incoming-webhook-notification/src/index.ts
- large-scale-notification/package.json
- large-scale-notification/src/httpTrigger.ts
- notification-codespaces/package.json
- notification-codespaces/src/index.js
- stocks-update-notification-bot/package.json
- stocks-update-notification-bot/src/timerTrigger.ts
- test-tool-sample-app/package.json
- test-tool-sample-app/src/cardActions/assignIncidentActionHandler.ts
- test-tool-sample-app/src/cardActions/doStuffActionHandler.ts
- test-tool-sample-app/src/cardActions/userLikeActionHandler.ts
- test-tool-sample-app/src/commands/helloworldCommandHandler.ts
- test-tool-sample-app/src/commands/helpCommandHandler.ts
- test-tool-sample-app/src/commands/heroCardCommandHandler.ts
- test-tool-sample-app/src/commands/learnCommandHandler.ts
- test-tool-sample-app/src/commands/reportIncidentCommandHandler.ts
- test-tool-sample-app/src/commands/showCardCommandHandler.ts
- test-tool-sample-app/src/commands/submitCommandHandler.ts
- test-tool-sample-app/src/index.ts
- test-tool-sample-app/src/simpleBot.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/28807683
> feat: remove adaptivecards-tools dependency

- intelligent-data-chart-generator/.vscode/tasks.json
- intelligent-data-chart-generator/api/tsconfig.json
- intelligent-data-chart-generator/index.html
- intelligent-data-chart-generator/package.json
- intelligent-data-chart-generator/src/App.tsx
- intelligent-data-chart-generator/src/internal/singletonContext.ts
- intelligent-data-chart-generator/src/services/callFunction.ts
- intelligent-data-chart-generator/teamsapp.local.yml
- intelligent-data-chart-generator/teamsapp.yml
- intelligent-data-chart-generator/tsconfig.app.json
- intelligent-data-chart-generator/tsconfig.json
- intelligent-data-chart-generator/tsconfig.node.json
- intelligent-data-chart-generator/vite.config.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/30111819
> fix: fix Intelligent Data Chart Generator sample

- test-tool-sample-app/.vscode/launch.json
- test-tool-sample-app/package.json
https://github.com/OfficeDev/teams-toolkit-samples/issues/1398
test-tool-sample-app just for show the test tool so remove the tasks: "Debug in Team", "Launch Remote "
after remove above, sample still could run in test tool
https://github.com/user-attachments/assets/cbd9b247-7749-4031-88df-c87df86f600f
> fix: remove unuse task for test-tool-sample-app

- command-bot-with-sso/src/index.ts
wrong if statement for autosignin check.
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/32982444
> fix: command-bot-sso signin fail

- copilot-connector-app/tabs/src/components/sample/lib/useData.ts
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/33996198
Bug introduced by: https://github.com/OfficeDev/microsoft-365-agents-toolkit-samples/pull/1472
Instead of including fetchDataAsync in the dependency array (which would recreate reload), store it in a ref and always call the latest version. To avoid infinite loop.
Verified:
> fix: avoid infinite loading status
